USE [WM_DB]
GO

/****** Object:  Table [dbo].[LOG_CARGA]    Script Date: 08/26/2013 14:12:04 ******/
IF  EXISTS (SELECT * FROM sys.objects WHERE object_id = OBJECT_ID(N'[dbo].[LOG_CARGA]') AND type in (N'U'))
DROP TABLE [dbo].[LOG_CARGA]
GO

USE [WM_DB]
GO

/****** Object:  Table [dbo].[LOG_CARGA]    Script Date: 08/26/2013 14:12:04 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

SET ANSI_PADDING OFF
GO

CREATE TABLE [dbo].[LOG_CARGA](
	[CD_LOG] [int] IDENTITY(1,1) NOT NULL,
	[CD_CARGA] [int] NOT NULL,
	[DT_CARGA] [smalldatetime] NULL,
	[CD_CARTEIRA] [varchar](15) NULL,
	[DS_DESCRICAO] [varchar](1000) NULL,
	[DT_LOG] [datetime] NOT NULL,
	[CD_USUARIO_RESPONSAVEL] [int] NULL,
	[IN_TIPO_MENSAGEM] [char](4) NULL,
 CONSTRAINT [PK_LOG_PROC] PRIMARY KEY CLUSTERED 
(
	[CD_LOG] ASC
)WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON) ON [PRIMARY]
) ON [PRIMARY]

GO

SET ANSI_PADDING OFF
GO

