USE [WM_DB]
GO

/****** Object:  StoredProcedure [dbo].[SP_WMDB_CARGA_POSICAO]    Script Date: 08/26/2013 14:15:04 ******/
IF  EXISTS (SELECT * FROM sys.objects WHERE object_id = OBJECT_ID(N'[dbo].[SP_WMDB_CARGA_POSICAO]') AND type in (N'P', N'PC'))
DROP PROCEDURE [dbo].[SP_WMDB_CARGA_POSICAO]
GO

USE [WM_DB]
GO

/****** Object:  StoredProcedure [dbo].[SP_WMDB_CARGA_POSICAO]    Script Date: 08/26/2013 14:15:04 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

create procedure [dbo].[SP_WMDB_CARGA_POSICAO] (@LISTA_CD_CARTEIRA VARCHAR(MAX) = null, @dt_inicio smalldatetime = null)
as

set nocount on

declare @table table
(
	CD varchar(15)
)

IF NOT @LISTA_CD_CARTEIRA IS NULL
BEGIN
	INSERT INTO @table (CD) 
	SELECT DISTINCT STRVAL FROM WM_DB.[dbo].[Split](@LISTA_CD_CARTEIRA, ',')			
END
	
if @dt_inicio is null
	begin
		DELETE z  FROM [WM_DB]..POSICAO z
			Inner Join (Select MIN(dt_inicial)'dt_inicio', MAX(dt_final) 'dt_fim', a.cd_carteira
							From WM_V_UBS_LOG_PROC_CARTEIRA a
							Inner Join log_processamento_carteira b
								on b.cd_carteira = a.cd_carteira
						Where a.DT > b.dt_carteira
						Group by a.cd_carteira) y
				on y.cd_carteira = z.CD_CARTEIRA
		where z.DT_POSICAO >= y.dt_inicio
		  and (z.CD_CARTEIRA in (select CD from @table) or @LISTA_CD_CARTEIRA is null)	
	end 	
else
	begin
		DELETE FROM [WM_DB]..POSICAO 
		WHERE (CD_CARTEIRA in (select CD from @table) or @LISTA_CD_CARTEIRA is null)	
		  AND DT_POSICAO >= @dt_inicio 
	end

/* INSERE POSICAO RENDA FIXA */
INSERT INTO [WM_DB]..Posicao
SELECT C.DT 'DT_POSICAO',
	   LTRIM(RTRIM(B.CLCLI_CD)) 'CD_CARTEIRA',
	   ltrim(rtrim(A.RFTP_CD)) + '_' + ltrim(rtrim(A.CD)) 'CD_ATIVO',
	   'RF' 'CD_TIPO_ATIVO',
	   C.DT_AQUISICAO,
	   D.VL_PU_PARTIDA 'PU_AQUISICAO',
	   CASE WHEN B.IC_ATIVO_PASSIVO = 'P' THEN C.VL_BRUTOPOS * -1                  
            WHEN B.IC_ATIVO_PASSIVO = 'A' THEN C.VL_BRUTOPOS                       
       END AS 'VL_SALDO_BRUTO',
       c.VL_PU 'PU_ATUAL', --C.VL_BRUTOPOS / (C.QT_DISPONIVEL + C.QT_BLOQUEADA)'PU_ATUAL',
	   C.VL_PROV_IRRF 'VL_IRRF',
       C.VL_PROV_IOF 'VL_IOF',
       C.QT_DISPONIVEL 'QT_DISP',
       C.QT_BLOQUEADA 'QT_BLOQUEADA',
       CASE WHEN B.IC_ATIVO_PASSIVO = 'P' THEN  C.VL_LIQ_POS * -1                  
            WHEN B.IC_ATIVO_PASSIVO = 'A' THEN  C.VL_LIQ_POS                       
       END AS 'VL_SALDO_LIQUIDO',
       NULL 'DT_LIQUIDACAO',
       NULL 'DS_HISTORICO',
       D.RFOP_CD 'COD_YMF',
       NULL 'VL_TAXA',
       C.RFOP_CD
  FROM [YMF_SAC]..SAC_RF_LASTRO A
  INNER JOIN [YMF_SAC]..SAC_RF_OPERACAO B
	ON B.RFLAS_CD = A.CD
  INNER JOIN [YMF_SAC]..SAC_RF_POS C
	ON C.RFOP_CD = B.CD
  INNER JOIN [YMF_SAC]..SAC_CL_PATRRF D
    ON D.RFOP_CD = B.CD
   AND D.CLCLI_CD = B.CLCLI_CD   
   AND D.DT = C.DT
  INNER JOIN WM_V_UBS_CLIENTE E
	ON E.CD_CARTEIRA = B.CLCLI_CD
  INNER JOIN YMF_SAC..RV_DATA_PROC F
	ON F.CODCLI = E.CD_CARTEIRA
  LEFT JOIN (select top 1 CD_CARTEIRA, 
					 DT_INICIO, 
					 DT_FIM 
			    from LOG_PROCESSAMENTO_CARTEIRA z 
			  where DT_FIM_PROC = (select MAX(DT_FIM_PROC) 
								     from LOG_PROCESSAMENTO_CARTEIRA 
								   where CD_CARTEIRA = z.CD_CARTEIRA)) G
	ON G.CD_CARTEIRA = E.CD_CARTEIRA
Where (b.CLCLI_CD in (select CD from @table) or @LISTA_CD_CARTEIRA is null)
  And C.DT >= ISNULL(@dt_inicio, G.DT_INICIO)
  --and C.DT >= (SELECT cONVERT(CHAR(4),YEAR(DATEADD(MONTH, -1, CL))) + '-' + RIGHT('00' + CONVERT(VARCHAR(2),MONTH(DATEADD(MONTH, -1, CL))), 2) + '-01' FROM YMF_SAC..RV_DATA_PROC WHERE CODCLI = E.CD_CARTEIRA)

/* INSERE POSICAO RENDA VARIÁVEL */
insert into [WM_DB]..Posicao
SELECT A.DT 'DT_POSICAO',
	   LTRIM(RTRIM(A.CLCLI_CD)) 'CD_CARTEIRA',
	   ltrim(rtrim(A.RVPAP_CD)) 'CD_ATIVO',
	   'RV' 'CD_TIPO_ATIVO',
	   NULL 'DT_AQUISICAO',
	   CONVERT(DECIMAL(20,6), (A.VL_CUSTOCOR / A.QT_TOTAL) * B.LOTECOT) 'PU_AQUISICAO',
	   A.VL_MERC 'VL_SALDO_BRUTO',
       A.VL_COTACAO 'PU_ATUAL',
	   A.VL_IRRF 'VL_IRRF',
       0 'VL_IOF',
       A.QT_DISPONIVEL 'QT_DISP',
       A.QT_TOTAL - A.QT_DISPONIVEL 'QT_BLOQUEADA',
       A.VL_MERC_LIQUIDO 'VL_SALDO_LIQUIDO',
       NULL 'DT_LIQUIDACAO',
       NULL 'DS_HISTORICO',
       LTRIM(RTRIM(A.RVPAP_CD)) + LTRIM(RTRIM(A.RVCOR_CD)) + LTRIM(RTRIM(A.CD_PRACA)) 'COD_YMF',
       NULL 'VL_TAXA',
       NULL CD_INTERNO
  FROM [YMF_SAC]..SAC_CL_PATRRV a
  INNER JOIN [YMF_SAC]..RV_CADPAP B
	ON A.RVPAP_CD = B.CODPAP
  INNER JOIN WM_V_UBS_CLIENTE E
	ON E.CD_CARTEIRA = A.CLCLI_CD	
  INNER JOIN YMF_SAC..RV_DATA_PROC F
	ON F.CODCLI = E.CD_CARTEIRA	
  LEFT JOIN (select top 1 CD_CARTEIRA, 
					 DT_INICIO, 
					 DT_FIM 
			    from LOG_PROCESSAMENTO_CARTEIRA z 
			  where DT_FIM_PROC = (select MAX(DT_FIM_PROC) 
								     from LOG_PROCESSAMENTO_CARTEIRA 
								   where CD_CARTEIRA = z.CD_CARTEIRA)) G
	ON G.CD_CARTEIRA = A.CLCLI_CD
Where (a.CLCLI_CD in (select CD from @table) or @LISTA_CD_CARTEIRA is null)
  And a.DT >= ISNULL(@dt_inicio, G.DT_INICIO)



/* INSERE POSICAO FUNDOS INVESTIMENTOS */
insert into [WM_DB]..Posicao
SELECT B.DT 'DT_POSICAO',
	   LTRIM(RTRIM(B.CLCLI_CD)) 'CD_CARTEIRA',
	   ltrim(rtrim(B.FICAD_CD)) 'CD_ATIVO',
	   'FI' 'CD_TIPO_ATIVO',
	   B.DT_APLICACAO 'DT_AQUISICAO',
	   B.VL_CUSTO 'PU_AQUISICAO',
	   B.VL_LIQ + B.VL_IRRF + B.VL_IOF 'VL_SALDO_BRUTO',
       B.VL_COTA 'PU_ATUAL',
	   B.VL_IRRF 'VL_IRRF',
       B.VL_IOF 'VL_IOF',
       B.QT_COTAS - B.QT_BLOQUEADA 'QT_DISP',
       B.QT_BLOQUEADA 'QT_BLOQUEADA',
       B.VL_LIQ 'VL_SALDO_LIQUIDO',
       NULL 'DT_LIQUIDACAO',
       NULL 'DS_HISTORICO',
       CONVERT(CHAR, b.DT_APLICACAO, 112) 'COD_YMF',
       NULL 'VL_TAXA',
       NULL 'CD_INTERNO'
	FROM [YMF_SAC]..SAC_FI_CADASTRO A
	INNER JOIN [YMF_SAC]..SAC_FI_POS B
		ON A.CD = B.FICAD_CD
    INNER JOIN WM_V_UBS_CLIENTE E
	    ON E.CD_CARTEIRA = B.CLCLI_CD			
    INNER JOIN YMF_SAC..RV_DATA_PROC F
		ON F.CODCLI = E.CD_CARTEIRA    
    LEFT JOIN (select top 1 CD_CARTEIRA, 
					 DT_INICIO, 
					 DT_FIM 
				  from LOG_PROCESSAMENTO_CARTEIRA z 
	  		    where DT_FIM_PROC = (select MAX(DT_FIM_PROC) 
									   from LOG_PROCESSAMENTO_CARTEIRA 
								     where CD_CARTEIRA = z.CD_CARTEIRA)) G
	    ON G.CD_CARTEIRA = B.CLCLI_CD	    	    
WHERE B.QT_COTAS <> 0
  AND A.BAMDA_CD = 'REAL'	
  And B.DT >= ISNULL(@dt_inicio, G.DT_INICIO)
  -- And B.DT >= (SELECT cONVERT(CHAR(4),YEAR(DATEADD(MONTH, -1, CL))) + '-' + RIGHT('00' + CONVERT(VARCHAR(2),MONTH(DATEADD(MONTH, -1, CL))), 2) + '-01' FROM YMF_SAC..RV_DATA_PROC WHERE CODCLI = E.CD_CARTEIRA)
  and (B.CLCLI_CD in (select CD from @table) or @LISTA_CD_CARTEIRA is null)  
UNION
SELECT B.DT 'DT_POSICAO',
	   LTRIM(RTRIM(B.CLCLI_CD)) 'CD_CARTEIRA',
	   ltrim(rtrim(B.FICAD_CD)) 'CD_ATIVO',
	   'FI' 'CD_TIPO_ATIVO',
	   B.DT_APLICACAO 'DT_AQUISICAO',
	   B.VL_CUSTO * D.VALORACU 'PU_AQUISICAO',
	   (B.VL_LIQ + B.VL_IRRF + B.VL_IOF)* D.VALORACU  'VL_SALDO_BRUTO',
       B.VL_COTA * D.VALORACU 'PU_ATUAL',
	   B.VL_IRRF * D.VALORACU 'VL_IRRF',
       B.VL_IOF * D.VALORACU 'VL_IOF',
       B.QT_COTAS - B.QT_BLOQUEADA 'QT_DISP',
       B.QT_BLOQUEADA 'QT_BLOQUEADA',
       B.VL_LIQ * D.VALORACU  'VL_SALDO_LIQUIDO',
       NULL 'DT_LIQUIDACAO',
       NULL 'DS_HISTORICO',
       CONVERT(CHAR, b.DT_APLICACAO, 112) 'COD_YMF', 
       NULL 'VL_TAXA',
       NULL 'CD_INTERNO'
	FROM [YMF_SAC]..SAC_FI_POS B
    INNER JOIN [YMF_SAC]..SAC_FI_CADASTRO A
		ON B.FICAD_CD = A.CD
	LEFT JOIN [YMF_SAC]..BAS_XRATE C
		ON A.BAMDA_CD = C.CODMOEDA1
    LEFT JOIN [YMF_SAC]..IDX_INDEX D
		ON C.INDEXADOR = D.CODINDEX 
	   AND B.DT = D.DATA
    INNER JOIN WM_V_UBS_CLIENTE E
	    ON E.CD_CARTEIRA = B.CLCLI_CD		   
	INNER JOIN YMF_SAC..RV_DATA_PROC F
	    ON F.CODCLI = E.CD_CARTEIRA	  
    LEFT JOIN (select top 1 CD_CARTEIRA, 
					 DT_INICIO, 
					 DT_FIM 
				  from LOG_PROCESSAMENTO_CARTEIRA z 
	  		    where DT_FIM_PROC = (select MAX(DT_FIM_PROC) 
									   from LOG_PROCESSAMENTO_CARTEIRA 
								     where CD_CARTEIRA = z.CD_CARTEIRA)) G
	    ON G.CD_CARTEIRA = B.CLCLI_CD
WHERE B.QT_COTAS <> 0
  AND A.BAMDA_CD <> 'REAL'	
  AND B.DT >= ISNULL(@dt_inicio, G.DT_INICIO)
  -- AND B.DT >= (SELECT cONVERT(CHAR(4),YEAR(DATEADD(MONTH, -1, CL))) + '-' + RIGHT('00' + CONVERT(VARCHAR(2),MONTH(DATEADD(MONTH, -1, CL))), 2) + '-01' FROM YMF_SAC..RV_DATA_PROC WHERE CODCLI = E.CD_CARTEIRA)
  and (B.CLCLI_CD in (select CD from @table) or @LISTA_CD_CARTEIRA is null)    
  
/* INSERE POSICAO EMPRÉSTIMO DE AÇÕES */
INSERT INTO [WM_DB]..POSICAO
SELECT A.DT_POSICAO 'DT_POSICAO',
	   B.CLCLI_CD 'CD_CARTEIRA',
       B.RVPAP_CD 'CD_ATIVO',
       'EA' 'CD_TIPO_ATIVO',
       B.DT_MOVIMENTO 'DT_AQUISICAO',
       A.VL_PRECO_CONTRATADO 'PU_AQUISICAO',
       C.VL_AJUSTADA_MTM_BRUTA 'VL_SALDO_BRUTO',
       CASE WHEN D.TIPORV = 'M' THEN A.VL_MEDIO ELSE A.VL_FECHAMENTO END 'PU_ATUAL',
       C.VL_IMPOSTO_RENDA 'VL_IRRF',
       0 'VL_IOF',
       0 'QT_DISP',
       B.QT_MOVIMENTADA 'QT_BLOQUEADA',
       C.VL_AJUSTADA_MTM_LIQUIDA 'VL_SALDO_LIQUIDO',
       NULL 'DT_LIQUIDACAO',
       NULL 'DS_HISTORICO',
       CONVERT(CHAR, A.ID_MOVIMENTO) 'COD_YMF',
      CASE WHEN 
          B.IC_TIPO_MOVIMENTO = 'T' THEN 
            (ABS(E.VL_TAXA_APROPRIADA) + ABS(F.VL_TAXA_APROPRIADA) )*-1
      ELSE 0 END AS 'VL_TAXA',
      NULL 'CD_INTERNO'
	FROM [YMF_SAC]..SAC_RV_EM_POS A
	INNER JOIN [YMF_SAC]..SAC_RV_EMPRESTIMO_ACOES B
		ON B.ID_MOVIMENTO = A.ID_MOVIMENTO
	INNER JOIN [YMF_SAC]..SAC_RV_EM_POS_REMUNERACAO C
		ON C.ID_MOVIMENTO = A.ID_MOVIMENTO
	   AND C.DT_POSICAO = A.DT_POSICAO 
	INNER JOIN [YMF_SAC]..CLI_BAS D
		ON D.CODCLI = B.CLCLI_CD
	INNER JOIN [YMF_SAC]..SAC_RV_EM_POS_COMISSAO E
		ON E.DT_POSICAO = A.DT_POSICAO
	   AND E.ID_MOVIMENTO = A.ID_MOVIMENTO
	INNER JOIN [YMF_SAC]..SAC_RV_EM_POS_TAXA_REGISTRO F
		ON F.DT_POSICAO = A.DT_POSICAO
	   AND F.ID_MOVIMENTO = A.ID_MOVIMENTO 
    INNER JOIN WM_V_UBS_CLIENTE G
	    ON G.CD_CARTEIRA = B.CLCLI_CD	   
	INNER JOIN YMF_SAC..RV_DATA_PROC H
	    ON H.CODCLI = G.CD_CARTEIRA	 	    
    LEFT JOIN (select top 1 CD_CARTEIRA, 
					 DT_INICIO, 
					 DT_FIM 
				  from LOG_PROCESSAMENTO_CARTEIRA z 
	  		    where DT_FIM_PROC = (select MAX(DT_FIM_PROC) 
									   from LOG_PROCESSAMENTO_CARTEIRA 
								     where CD_CARTEIRA = z.CD_CARTEIRA)) I
	    ON I.CD_CARTEIRA = B.CLCLI_CD		    
 WHERE A.QT_EMPRESTIMO <> 0
  AND A.DT_POSICAO >= ISNULL(@dt_inicio, I.DT_INICIO)
   --and A.DT_POSICAO >= (SELECT cONVERT(CHAR(4),YEAR(DATEADD(MONTH, -1, CL))) + '-' + RIGHT('00' + CONVERT(VARCHAR(2),MONTH(DATEADD(MONTH, -1, CL))), 2) + '-01' FROM YMF_SAC..RV_DATA_PROC WHERE CODCLI = G.CD_CARTEIRA)
  AND (B.CLCLI_CD in (select CD from @table) or @LISTA_CD_CARTEIRA is null)   
 
/* INSERE POSICAO FUTUROS */
INSERT INTO [WM_DB]..POSICAO
SELECT A.DT 'DT_POSICAO',
	   A.CLCLI_CD 'CD_CARTEIRA',
       A.FUVCT_FUATV_CD+A.FUVCT_CD 'CD_ATIVO',
       'FU' 'CD_TIPO_ATIVO',
       NULL 'DT_AQUISICAO',
       B.VL_PRECOMERC 'PU_AQUISICAO',
       B.VL_PRECOMERC 'VL_SALDO_BRUTO',
       A.VL_PRECOMERC 'PU_ATUAL',
       0 'VL_IRRF',
       0 'VL_IOF',       
       B.QT 'QT_DISP',
       0 'QT_BLOQUEADA',
       B.VL_PRECOMERC 'VL_SALDO_LIQUIDO',       
       NULL 'DT_LIQUIDACAO',
       NULL 'DS_HISTORICO',
       B.RVCOR_CD 'COD_YMF',
       0 'VL_TAXA',
       NULL 'CD_INTERNO'
  FROM [YMF_SAC]..SAC_FU_POS A
  INNER JOIN [YMF_SAC]..SAC_CL_PATRFUT B
	ON B.CLCLI_CD = A.CLCLI_CD 
   AND B.DT = A.DT
   AND B.FUVCT_CD = A.FUVCT_CD
   AND B.RVCOR_CD = A.RVCOR_CD
   AND B.FUATV_CD = A.FUVCT_FUATV_CD
  INNER JOIN WM_V_UBS_CLIENTE C
	ON C.CD_CARTEIRA = A.CLCLI_CD	   
  INNER JOIN YMF_SAC..RV_DATA_PROC D
    ON D.CODCLI = C.CD_CARTEIRA
  LEFT JOIN (select top 1 CD_CARTEIRA, 
					 DT_INICIO, 
					 DT_FIM 
			    from LOG_PROCESSAMENTO_CARTEIRA z
  			  where DT_FIM_PROC = (select MAX(DT_FIM_PROC) 
			  					     from LOG_PROCESSAMENTO_CARTEIRA 
							       where CD_CARTEIRA = z.CD_CARTEIRA)) G
    ON G.CD_CARTEIRA = A.CLCLI_CD
 WHERE A.DT >= ISNULL(@dt_inicio, G.DT_INICIO)
-- A.DT >= (SELECT cONVERT(CHAR(4),YEAR(DATEADD(MONTH, -1, CL))) + '-' + RIGHT('00' + CONVERT(VARCHAR(2),MONTH(DATEADD(MONTH, -1, CL))), 2) + '-01' FROM YMF_SAC..RV_DATA_PROC WHERE CODCLI = C.CD_CARTEIRA)
   and (A.CLCLI_CD in (select CD from @table) or @LISTA_CD_CARTEIRA is null)   	   

	
/* INSERE POSICAO SWAP */
INSERT INTO [WM_DB]..POSICAO
SELECT A.DT 'DT_POSICAO',
	   A.CLCLI_CD 'CD_CARTEIRA',
       C.CD 'CD_ATIVO',
       'SW' 'CD_TIPO_ATIVO',
       C.DT_PARTIDA 'DT_AQUISICAO',
       A.VL_APROP_LIQ 'PU_AQUISICAO',
       A.VL_APROP_BRUTO * A.VL_COR_CAMBIO 'VL_SALDO_BRUTO',
       A.QT * A.VL_COR_CAMBIO 'PU_ATUAL',
       A.VL_APROP_IRRF * A.VL_COR_CAMBIO 'VL_IRRF',
       0 'VL_IOF',
       A.QT 'QT_DISP',
       0 'QT_BLOQUEADA',
       A.VL_APROP_LIQ * A.VL_COR_CAMBIO 'VL_SALDO_LIQUIDO',
       NULL DT_LIQUIDACAO,
       NULL DS_HISTORICO,
       C.CD 'COD_YMF',
       0 'VL_TAXA',
       NULL 'CD_INTERNO'
  FROM [YMF_SAC]..SAC_SW2_POS A	
  INNER JOIN [YMF_SAC]..SAC_SW2_MOV B
	ON B.SWCAD_CD = A.SWCAD_CD
  INNER JOIN [YMF_SAC]..SAC_SW_CAD C
	ON C.CD = B.SWCAD_CD
   AND C.CD = A.SWCAD_CD
  INNER JOIN WM_V_UBS_CLIENTE D
	ON D.CD_CARTEIRA = A.CLCLI_CD
  INNER JOIN YMF_SAC..RV_DATA_PROC E
    ON E.CODCLI = D.CD_CARTEIRA
  LEFT JOIN (select top 1 CD_CARTEIRA, 
					 DT_INICIO, 
					 DT_FIM 
			    from LOG_PROCESSAMENTO_CARTEIRA z 
  			  where DT_FIM_PROC = (select MAX(DT_FIM_PROC) 
			  					     from LOG_PROCESSAMENTO_CARTEIRA 
							       where CD_CARTEIRA = z.CD_CARTEIRA)) G
    ON G.CD_CARTEIRA = A.CLCLI_CD
 WHERE A.DT >= ISNULL(@dt_inicio, G.DT_INICIO)
--A.DT >= (SELECT cONVERT(CHAR(4),YEAR(DATEADD(MONTH, -1, CL))) + '-' + RIGHT('00' + CONVERT(VARCHAR(2),MONTH(DATEADD(MONTH, -1, CL))), 2) + '-01' FROM YMF_SAC..RV_DATA_PROC WHERE CODCLI = D.CD_CARTEIRA)
   and (A.CLCLI_CD in (select CD from @table) or @LISTA_CD_CARTEIRA is null)   		

/* INSERE POSICAO TESOURARIA */
INSERT INTO [WM_DB]..POSICAO
SELECT A.DT 'DT_POSICAO',
	   A.CLCLI_CD 'CD_CARTEIRA', 
       '251' 'CD_ATIVO',     
       'TE' 'CD_TIPO_ATIVO',
       A.DT 'DT_AQUISICAO',
       NULL 'PU_AQUISICAO',
       A.VL_CCTE_ADM 'VL_SALDO_BRUTO',
       A.VL_CCTE_ADM 'PU_ATUAL',      
       NULL 'VL_IRRF',
       NULL 'VL_IOF',
       NULL 'QT_DISP',
       0 'QT_BLOQUEADA',       
       A.VL_CCTE_ADM 'VL_SALDO_LIQUIDO',
       NULL DT_LIQUIDACAO,
       NULL DS_HISTORICO,
       CLCLI_CD 'COD_YMF',
       0 'VL_TAXA',
       NULL 'CD_INTERNO'
	FROM [YMF_SAC]..SAC_CL_PATR A
	INNER JOIN WM_V_UBS_CLIENTE B
	  ON B.CD_CARTEIRA = A.CLCLI_CD	   
    INNER JOIN YMF_SAC..RV_DATA_PROC C
      ON C.CODCLI = B.CD_CARTEIRA	  
	LEFT JOIN (select top 1 CD_CARTEIRA, 
						 DT_INICIO, 
						 DT_FIM 
					from LOG_PROCESSAMENTO_CARTEIRA z 
  				  where DT_FIM_PROC = (select MAX(DT_FIM_PROC) 
			  							 from LOG_PROCESSAMENTO_CARTEIRA 
									   where CD_CARTEIRA = z.CD_CARTEIRA)) G
	  ON G.CD_CARTEIRA = A.CLCLI_CD      
 WHERE A.DT >= ISNULL(@dt_inicio, G.DT_INICIO)
 --A.DT >= (SELECT cONVERT(CHAR(4),YEAR(DATEADD(MONTH, -1, CL))) + '-' + RIGHT('00' + CONVERT(VARCHAR(2),MONTH(DATEADD(MONTH, -1, CL))), 2) + '-01' FROM YMF_SAC..RV_DATA_PROC WHERE CODCLI = B.CD_CARTEIRA)
   and (A.CLCLI_CD in (select CD from @table) or @LISTA_CD_CARTEIRA is null)   		  

/* INSERE POSICAO CONTAS A PAGAR E RECEBER */
INSERT INTO [WM_DB]..POSICAO
SELECT A.DT 'DT_POSICAO',
	   A.CLCLI_CD 'CD_CARTEIRA',
       A.MTTP_CD 'CD_ATIVO',
       'CP' 'CD_TIPO_ATIVO',
       NULL 'DT_AQUISICAO',
       NULL 'PU_AQUISICAO',
       A.VL 'VL_SALDO_BRUTO',
       A.VL 'PU_ATUAL',
       NULL 'VL_IRRF',
       NULL 'VL_IOF',
	   NULL 'QT_DISP',
       NULL 'QT_BLOQUEADA',
       A.VL 'VL_SALDO_LIQUIDO',       
       DT_LIQUIDACAO 'DT_LIQUIDACAO',
       DS DS_HISTORICO,
       CONVERT(CHAR, A.ID) 'COD_YMF',
        0 'VL_TAXA',
        NULL 'CD_INTERNO'
  FROM [YMF_SAC]..SAC_CL_CPR A
  INNER JOIN WM_V_UBS_CLIENTE B
    ON B.CD_CARTEIRA = A.CLCLI_CD	      
  INNER JOIN YMF_SAC..RV_DATA_PROC C
    ON C.CODCLI = B.CD_CARTEIRA	    
  LEFT JOIN (select top 1 CD_CARTEIRA, 
						 DT_INICIO, 
						 DT_FIM 
					from LOG_PROCESSAMENTO_CARTEIRA z 
  				  where DT_FIM_PROC = (select MAX(DT_FIM_PROC) 
			  							 from LOG_PROCESSAMENTO_CARTEIRA 
									   where CD_CARTEIRA = z.CD_CARTEIRA)) G
   ON G.CD_CARTEIRA = A.CLCLI_CD      
WHERE A.MTTP_CD IS NOT NULL
   AND A.MTTP_CD <> '251'  
   AND A.DT >= ISNULL(@dt_inicio, G.DT_INICIO)
--   and A.DT >= (SELECT cONVERT(CHAR(4),YEAR(DATEADD(MONTH, -1, CL))) + '-' + RIGHT('00' + CONVERT(VARCHAR(2),MONTH(DATEADD(MONTH, -1, CL))), 2) + '-01' FROM YMF_SAC..RV_DATA_PROC WHERE CODCLI = B.CD_CARTEIRA)
   and (A.CLCLI_CD in (select CD from @table) or @LISTA_CD_CARTEIRA is null)   	    

/* INSERE POSICAO CAMBIO */
INSERT INTO [WM_DB]..POSICAO
SELECT A.DT 'DT_POSICAO',
	   A.CLCLI_CD 'CD_CARTEIRA',
       A.FICAD_CD 'CD_ATIVO',
       'CB' 'CD_TIPO_ATIVO',
       A.DT_APLICACAO 'DT_AQUISICAO',
       NULL 'PU_AQUISICAO',
       A.VL_RENDIMENTO 'VL_SALDO_BRUTO',
       NULL 'PU_ATUAL',      
       NULL 'VL_IRRF',
       NULL 'VL_IOF',
       NULL 'QT_DISP',
       NULL 'QT_BLOQUEADA',
       NULL 'VL_SALDO_LIQUIDO',
       NULL DT_LIQUIDACAO,
       NULL DS_HISTORICO,
	   CONVERT(CHAR, A.DT_APLICACAO, 112) 'COD_YMF',
       0 'VL_TAXA',
       NULL 'CD_INTERNO'
      FROM [YMF_SAC]..SAC_FI_POS A
      INNER JOIN [YMF_SAC]..SAC_CB_MOVIMENTO B 
         ON B.CD_ATIVO = A.FICAD_CD
        AND RTRIM(A.CLCLI_CD) = RTRIM(B.CLCLI_CD)
	  INNER JOIN WM_V_UBS_CLIENTE C
         ON C.CD_CARTEIRA = A.CLCLI_CD	        
	  INNER JOIN YMF_SAC..RV_DATA_PROC D
		 ON D.CODCLI = C.CD_CARTEIRA
	  LEFT JOIN (select top 1 CD_CARTEIRA, 
						 DT_INICIO, 
						 DT_FIM 
					from LOG_PROCESSAMENTO_CARTEIRA z 
  				  where DT_FIM_PROC = (select MAX(DT_FIM_PROC) 
			  							 from LOG_PROCESSAMENTO_CARTEIRA 
									   where CD_CARTEIRA = z.CD_CARTEIRA)) G	
		ON G.CD_CARTEIRA = A.CLCLI_CD     									   	 	             
     WHERE B.IC_FORWARD <> 'V'
       AND B.IC_TIPO_OPERACAO = 'N'   
	   AND A.DT >= ISNULL(@dt_inicio, G.DT_INICIO)
--       AND A.DT >= (SELECT cONVERT(CHAR(4),YEAR(DATEADD(MONTH, -1, CL))) + '-' + RIGHT('00' + CONVERT(VARCHAR(2),MONTH(DATEADD(MONTH, -1, CL))), 2) + '-01' FROM YMF_SAC..RV_DATA_PROC WHERE CODCLI = C.CD_CARTEIRA)
	   AND (A.CLCLI_CD in (select CD from @table) or @LISTA_CD_CARTEIRA is null)   	       
 
GO

