USE [WM_DB]
GO

/****** Object:  StoredProcedure [dbo].[SP_WMDB_CARGA_CARTEIRA]    Script Date: 08/26/2013 14:13:25 ******/
IF  EXISTS (SELECT * FROM sys.objects WHERE object_id = OBJECT_ID(N'[dbo].[SP_WMDB_CARGA_CARTEIRA]') AND type in (N'P', N'PC'))
DROP PROCEDURE [dbo].[SP_WMDB_CARGA_CARTEIRA]
GO

USE [WM_DB]
GO

/****** Object:  StoredProcedure [dbo].[SP_WMDB_CARGA_CARTEIRA]    Script Date: 08/26/2013 14:13:25 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

Create Procedure [dbo].[SP_WMDB_CARGA_CARTEIRA]
As

Set Nocount On 

INSERT INTO WM_DB..CARTEIRA 
(CD_CARTEIRA, NO_CARTEIRA, CD_INDEX, NU_CGC, IN_ATIVO_INATIVO, CD_CLIENTE, 
 DT_ABERTURA, DT_ENCERRAMENTO, CD_PERFIL_RISCO, CD_ADMINISTRADOR, CD_CUSTODIANTE, 
 CD_GESTOR, CD_USUARIO_CA, IN_TIPO_PESSOA, CD_MOEDA, IN_TIPO_CARTEIRA)
SELECT  CD_CARTEIRA, NO_CARTEIRA, CD_INDEX, NU_CGC,
		SG_STATUS, 
		NULL AS CD_CLIENTE,
		DT_ABERTURA,
		DT_ENCERRAMENTO,
		CD_RISCO_PERFIL,
		CD_ADMINISTRADOR,
		CD_CUSTODIANTE,
		CD_GESTOR,
		CD_USUARIO_CA,
		IN_TIPO_PESSOA,
		CD_MOEDA,
		IN_TIPO_CARTEIRA
FROM WM_V_UBS_CLIENTE
WHERE CD_CARTEIRA NOT IN (SELECT CD_CARTEIRA FROM WM_DB..CARTEIRA)

UPDATE WM_DB..CARTEIRA 
	SET NO_CARTEIRA = A.NO_CARTEIRA, 
		CD_INDEX = A.CD_INDEX, 
		NU_CGC = A.NU_CGC, 
		IN_ATIVO_INATIVO = A.SG_STATUS, 
		CD_CLIENTE = NULL, 
		DT_ABERTURA = A.DT_ABERTURA, 
		DT_ENCERRAMENTO = A.DT_ENCERRAMENTO, 
		CD_PERFIL_RISCO = A.CD_RISCO_PERFIL, 
		CD_ADMINISTRADOR = A.CD_ADMINISTRADOR, 
		CD_CUSTODIANTE = A.CD_CUSTODIANTE, 
		CD_GESTOR = A.CD_GESTOR, 
		CD_USUARIO_CA = A.CD_USUARIO_CA,
		IN_TIPO_PESSOA = A.IN_TIPO_PESSOA,
		CD_MOEDA = A.CD_MOEDA,
		IN_TIPO_CARTEIRA = A.IN_TIPO_CARTEIRA
FROM WM_V_UBS_CLIENTE A
INNER JOIN WM_DB..CARTEIRA B
	ON A.CD_CARTEIRA = B.CD_CARTEIRA


GO

