USE [WM_DB]
GO

/****** Object:  StoredProcedure [dbo].[SP_WMDB_CARGA_ATIVOS]    Script Date: 08/26/2013 14:14:54 ******/
IF  EXISTS (SELECT * FROM sys.objects WHERE object_id = OBJECT_ID(N'[dbo].[SP_WMDB_CARGA_ATIVOS]') AND type in (N'P', N'PC'))
DROP PROCEDURE [dbo].[SP_WMDB_CARGA_ATIVOS]
GO

USE [WM_DB]
GO

/****** Object:  StoredProcedure [dbo].[SP_WMDB_CARGA_ATIVOS]    Script Date: 08/26/2013 14:14:54 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

Create Procedure [dbo].[SP_WMDB_CARGA_ATIVOS] 
AS
Set Nocount On 

/* SCRIPT RESPONSÁVEL PELA ATUALIZAÇÃO DAS TABELAS DE ATIVOS */

/* Renda Fixa */
INSERT INTO WM_DB..ATIVOS
(CD_ATIVO, CD_TIPO_ATIVO, NO_ATIVO, CD_CLASSE_ATIVO, CD_ISIN)
SELECT A.CD_ATIVO, 'RF', A.NO_ATIVO, NULL, A.CD_ISIN 
FROM WM_V_UBS_ATIVOS_RF A
WHERE NOT EXISTS (SELECT CD_ATIVO FROM WM_DB..ATIVOS WHERE CD_TIPO_ATIVO = 'RF' AND CD_ATIVO = A.CD_ATIVO)

UPDATE WM_DB..ATIVOS
	SET NO_ATIVO = A.NO_ATIVO,
		CD_CLASSE_ATIVO = A.CD_CLASSE_ATIVO,
		CD_ISIN = A.CD_ISIN
FROM WM_V_UBS_ATIVOS_RF A
INNER JOIN WM_DB..ATIVOS B
	ON B.CD_ATIVO = A.CD_ATIVO
WHERE B.CD_TIPO_ATIVO = 'RF'

INSERT INTO WM_DB..ATIVOS_RF
(CD_ATIVO, CD_TIPO_ATIVO, CD_LASTRO, PU_EMISSAO, PU_BASE, CD_TIPO_MTM, PC_MTM, CD_INDEX_MTM, 
 VL_TAXA, DT_DATA_BASE, CD_INDEXADOR, DT_EMISSAO, DT_VENCIMENTO, CD_EMISSOR, NU_PRZ_LIQUIDACAO, IN_PRE_POS, PC_INDEXADOR, 
 CD_TIPO_ATIVO_RF, IN_PUBLICO_PRIVADO, CD_MOEDA, CD_PAIS, IN_CONDICAO_RESGATE, NU_DIAS_PRAZO_LIQ, QT_CUPOM_ANO, IN_ATIVO_PASSIVO)
Select cd_ativo, 'RF', CD_LASTRO,vl_pu_emissao, vl_pu_base, cd_tipo_mtm, pc_mtm, cd_indexador, 
       vl_taxa, dt_data_base, cd_indexador, dt_emissao, dt_vencimento, cd_emissor, NU_PRZ_LIQUIDACAO, IN_PRE_POS, PC_INDEXADOR, 
       CD_TIPO_RF, IN_PUB_PRIV, CD_MOEDA, CD_PAIS, CD_CONDICAO_RESGATE, NU_DIAS_PRAZO_LIQ, QT_CUPOM_ANO, IN_ATIVO_PASSIVO
From WM_V_UBS_ATIVOS_RF A
Where NOT EXISTS (SELECT CD_ATIVO FROM WM_DB..ATIVOS_RF WHERE CD_ATIVO = A.CD_ATIVO)

UPDATE WM_DB..ATIVOS_RF
	SET CD_LASTRO = A.CD_LASTRO,
		PU_EMISSAO = A.vl_pu_emissao,
		PU_BASE = A.vl_pu_base,
		CD_TIPO_MTM = A.CD_TIPO_MTM,
		PC_MTM = A.PC_MTM,
		CD_INDEX_MTM = A.cd_indexador,
		VL_TAXA = A.vl_taxa,
		DT_DATA_BASE = A.DT_DATA_BASE,
		CD_INDEXADOR = A.CD_INDEXADOR,
		DT_EMISSAO = A.DT_EMISSAO,
		DT_VENCIMENTO = A.DT_VENCIMENTO,
		CD_EMISSOR = A.CD_EMISSOR,
		NU_PRZ_LIQUIDACAO = A.NU_PRZ_LIQUIDACAO,
		IN_PRE_POS = A.IN_PRE_POS,
		PC_INDEXADOR = A.PC_INDEXADOR,
		CD_TIPO_ATIVO_RF = A.CD_TIPO_RF,
		IN_PUBLICO_PRIVADO = A.IN_PUB_PRIV,
		CD_MOEDA = A.CD_MOEDA,
		CD_PAIS = A.CD_PAIS,
		IN_CONDICAO_RESGATE = A.CD_CONDICAO_RESGATE,
		NU_DIAS_PRAZO_LIQ = A.NU_DIAS_PRAZO_LIQ,
		QT_CUPOM_ANO = A.QT_CUPOM_ANO,
		IN_ATIVO_PASSIVO = A.IN_ATIVO_PASSIVO
FROM WM_V_UBS_ATIVOS_RF A
INNER JOIN WM_DB..ATIVOS_RF B
	ON B.CD_ATIVO = A.CD_ATIVO		
	
/* Renda Variável */
INSERT INTO WM_DB..ATIVOS
(CD_ATIVO, CD_TIPO_ATIVO, NO_ATIVO, CD_CLASSE_ATIVO, CD_ISIN)
SELECT CD_ATIVO, 'RV', NO_ATIVO, NULL, CD_ISIN 
FROM WM_V_UBS_ATIVOS_RV A
WHERE NOT EXISTS (SELECT CD_ATIVO FROM WM_DB..ATIVOS WHERE CD_TIPO_ATIVO = 'RV' AND CD_ATIVO = A.CD_ATIVO)

UPDATE WM_DB..ATIVOS
	SET NO_ATIVO = A.NO_ATIVO,
		CD_CLASSE_ATIVO = A.CD_CLASSE_ATIVO,
		CD_ISIN = A.CD_ISIN
FROM WM_V_UBS_ATIVOS_RV A
INNER JOIN WM_DB..ATIVOS B
	ON B.CD_ATIVO = A.CD_ATIVO
WHERE B.CD_TIPO_ATIVO = 'RV'	

insert into WM_DB..ATIVOS_RV
(CD_ATIVO, CD_TIPO_ATIVO, CD_CUSTODIA, CD_ADMINISTRADOR, NU_DIAS_LIQ, VL_EXERCICIO, CD_ATIVO_OBJETO, DT_VENCIMENTO, CD_TIPO_ATIVO_RV, CD_OPCAO)
select CD_ATIVO, 'RV', CD_BOLSA, CD_EMP, PRZ_LIQUI, VL_EXERC, CD_ATIVO_OBJETO, DT_VENCIMENTO, CD_TIPO_ATIVO, CD_OPCAO
from WM_V_UBS_ATIVOS_RV A
Where NOT EXISTS (SELECT CD_ATIVO FROM WM_DB..ATIVOS_RV WHERE CD_ATIVO = A.CD_ATIVO)

UPDATE WM_DB..ATIVOS_RV
	SET CD_CUSTODIA = A.CD_BOLSA,
		CD_ADMINISTRADOR = A.CD_EMP,
		NU_DIAS_LIQ = A.PRZ_LIQUI,
		VL_EXERCICIO = A.VL_EXERC,
		CD_ATIVO_OBJETO = A.CD_ATIVO_OBJETO,
		DT_VENCIMENTO = A.DT_VENCIMENTO,
		CD_TIPO_ATIVO_RV = A.CD_TIPO_ATIVO,
		CD_OPCAO = A.CD_OPCAO
FROM WM_V_UBS_ATIVOS_RV A
INNER JOIN WM_DB..ATIVOS_RV B
	ON B.CD_ATIVO = A.CD_ATIVO			
	
/* Cotas de Investimento */
INSERT INTO WM_DB..ATIVOS
(CD_ATIVO, CD_TIPO_ATIVO, NO_ATIVO, CD_CLASSE_ATIVO, CD_ISIN)
SELECT CD_ATIVO, 'FI', NO_ATIVO, NULL, CD_ISIN 
FROM WM_V_UBS_ATIVOS_FI A
WHERE NOT EXISTS (SELECT CD_ATIVO FROM WM_DB..ATIVOS WHERE CD_TIPO_ATIVO = 'FI' AND CD_ATIVO = A.CD_ATIVO)

UPDATE WM_DB..ATIVOS
	SET NO_ATIVO = A.NO_ATIVO,
		CD_CLASSE_ATIVO = A.CD_CLASSE_ATIVO,
		CD_ISIN = A.CD_ISIN
FROM WM_V_UBS_ATIVOS_FI A
INNER JOIN WM_DB..ATIVOS B
	ON B.CD_ATIVO = A.CD_ATIVO
WHERE B.CD_TIPO_ATIVO = 'FI'	

INSERT INTO WM_DB..ATIVOS_FI
(CD_ATIVO, CD_TIPO_ATIVO, CD_TIPO_FUNDO, CD_ADMINISTRADOR, CD_CUSTODIANTE, CD_GESTOR, CD_INDEX, CD_MOEDA, CD_CLASSIFICACAO_CVM,
 NU_CNPJ, NU_DIAS_LIQUI_FIS_RESG, NU_DIAS_LIQUI_FIN_RESG, NU_DIAS_LIQUI_FIS_APLIC, NU_DIAS_LIQUI_FIN_APLIC)
SELECT CD_ATIVO, 'FI', CD_TIPO_FUNDO, CD_ADMINISTRADOR, CD_CUSTODIANTE, CD_GESTOR, CD_INDEX, CD_MOEDA, CD_CLASSIFICACAO_CVM,
       NU_CNPJ, NU_DIAS_LIQUI_FIS_RESG, NU_DIAS_LIQUI_FIN_RESG, NU_DIAS_LIQUI_FIS_APLIC, NU_DIAS_LIQUI_FIN_APLIC
FROM WM_V_UBS_ATIVOS_FI A
Where NOT EXISTS (SELECT CD_ATIVO FROM WM_DB..ATIVOS_FI WHERE CD_ATIVO = A.CD_ATIVO)

UPDATE WM_DB..ATIVOS_FI
	SET CD_TIPO_FUNDO = A.CD_TIPO_FUNDO,
		CD_ADMINISTRADOR = A.CD_ADMINISTRADOR,
		CD_CUSTODIANTE = A.CD_CUSTODIANTE,
		CD_GESTOR = A.CD_GESTOR,
		CD_INDEX = A.CD_INDEX,
		CD_MOEDA = A.CD_MOEDA,
		CD_CLASSIFICACAO_CVM = A.CD_CLASSIFICACAO_CVM,
		NU_CNPJ = A.NU_CNPJ, 
		NU_DIAS_LIQUI_FIS_RESG = A.NU_DIAS_LIQUI_FIS_RESG, 
		NU_DIAS_LIQUI_FIN_RESG = A.NU_DIAS_LIQUI_FIN_RESG, 
		NU_DIAS_LIQUI_FIS_APLIC = A.NU_DIAS_LIQUI_FIS_APLIC, 
		NU_DIAS_LIQUI_FIN_APLIC = A.NU_DIAS_LIQUI_FIN_APLIC
FROM WM_V_UBS_ATIVOS_FI A
INNER JOIN WM_DB..ATIVOS_FI B
	ON B.CD_ATIVO = A.CD_ATIVO	
	
/* Índices */
INSERT INTO WM_DB..ATIVOS
(CD_ATIVO, CD_TIPO_ATIVO, NO_ATIVO, CD_CLASSE_ATIVO, CD_ISIN)
SELECT CD_ATIVO, 'IX', case when isnull(NO_ATIVO, '') = '' then CD_ATIVO else NO_ATIVO end  , null, null 
FROM WM_V_UBS_ATIVOS_IDX A
WHERE NOT EXISTS(SELECT CD_ATIVO FROM WM_DB..ATIVOS WHERE CD_TIPO_ATIVO = 'IX' AND CD_ATIVO = A.CD_ATIVO)

UPDATE WM_DB..ATIVOS
	SET NO_ATIVO = case when isnull(a.NO_ATIVO, '') = '' then a.CD_ATIVO else a.NO_ATIVO end 
FROM WM_V_UBS_ATIVOS_IDX A
INNER JOIN WM_DB..ATIVOS B
	ON B.CD_ATIVO = A.CD_ATIVO
WHERE B.CD_TIPO_ATIVO = 'IX'	

INSERT INTO WM_DB..ATIVOS_IDX
(CD_ATIVO, CD_TIPO_ATIVO, IN_FUNDO)
SELECT CD_ATIVO, 'IX', IN_FUNDO
FROM WM_V_UBS_ATIVOS_IDX A
Where NOT EXISTS (SELECT CD_ATIVO FROM WM_DB..ATIVOS_IDX WHERE CD_ATIVO = A.CD_ATIVO)

UPDATE WM_DB..ATIVOS_IDX
	SET IN_FUNDO = A.IN_FUNDO
FROM WM_V_UBS_ATIVOS_IDX A
INNER JOIN WM_DB..ATIVOS_IDX B
	ON B.CD_ATIVO = A.CD_ATIVO	

/* Tesouraria */
INSERT INTO WM_DB..ATIVOS
(CD_ATIVO, CD_TIPO_ATIVO, NO_ATIVO, CD_CLASSE_ATIVO, CD_ISIN)
SELECT CD_ATIVO, 'TE', NO_ATIVO, null, null 
FROM WM_V_UBS_ATIVOS_TE A
WHERE NOT EXISTS (SELECT CD_ATIVO FROM WM_DB..ATIVOS WHERE CD_TIPO_ATIVO = 'TE' AND CD_ATIVO = A.CD_ATIVO)

UPDATE WM_DB..ATIVOS
	SET NO_ATIVO = A.NO_ATIVO
FROM WM_V_UBS_ATIVOS_TE A
INNER JOIN WM_DB..ATIVOS B
	ON B.CD_ATIVO = A.CD_ATIVO
WHERE B.CD_TIPO_ATIVO = 'TE'	

INSERT INTO WM_DB..ATIVOS_TE
(CD_ATIVO, CD_TIPO_ATIVO)
SELECT CD_ATIVO, 'TE'
FROM WM_V_UBS_ATIVOS_TE A
Where NOT EXISTS (SELECT CD_ATIVO FROM WM_DB..ATIVOS_TE WHERE CD_ATIVO = A.CD_ATIVO)

/* Empréstimos de Ações */
INSERT INTO WM_DB..ATIVOS
(CD_ATIVO, CD_TIPO_ATIVO, NO_ATIVO, CD_CLASSE_ATIVO, CD_ISIN)
SELECT CD_ATIVO, 'EA', NO_ATIVO, null, CD_ISIN 
FROM WM_V_UBS_ATIVOS_EA A
WHERE NOT EXISTS (SELECT CD_ATIVO FROM WM_DB..ATIVOS WHERE CD_TIPO_ATIVO = 'EA' AND CD_ATIVO = A.CD_ATIVO)

UPDATE WM_DB..ATIVOS
	SET NO_ATIVO = A.NO_ATIVO,
		CD_CLASSE_ATIVO = A.CD_CLASSE_ATIVO,
		CD_ISIN = A.CD_ISIN
FROM WM_V_UBS_ATIVOS_EA A
INNER JOIN WM_DB..ATIVOS B
	ON B.CD_ATIVO = A.CD_ATIVO
WHERE B.CD_TIPO_ATIVO = 'EA'	

INSERT INTO WM_DB..ATIVOS_BTC
(CD_ATIVO, CD_TIPO_ATIVO, IN_TIPO_BTC, CD_CUSTODIANTE, CD_ADMINISTRADOR, IN_PRAZO_LIQUIDACAO, VL_EXERCICIO, CD_OPCAO, DT_VENCIMENTO, CD_ATIVO_OBJETO)
SELECT CD_ATIVO, 'EA', CD_TIPO_EA, CD_BOLSA, CD_ADMINISTRADOR, PRZ_LIQUI, VL_EXERC, CD_OPCAO, DT_VENCIMENTO, CD_ATIVO_OBJETO
FROM WM_V_UBS_ATIVOS_EA A
WHERE NOT EXISTS (SELECT CD_ATIVO FROM WM_DB..ATIVOS_BTC WHERE CD_ATIVO = A.CD_ATIVO)

UPDATE WM_DB..ATIVOS_BTC
	SET IN_TIPO_BTC = A.CD_TIPO_EA, 
		CD_CUSTODIANTE = A.CD_BOLSA, 
		CD_ADMINISTRADOR = A.CD_ADMINISTRADOR, 
		IN_PRAZO_LIQUIDACAO = A.PRZ_LIQUI, 
		VL_EXERCICIO = A.VL_EXERC, 
		CD_OPCAO = A.CD_OPCAO, 
		DT_VENCIMENTO = A.DT_VENCIMENTO, 
		CD_ATIVO_OBJETO = A.CD_ATIVO_OBJETO
FROM WM_V_UBS_ATIVOS_EA A
INNER JOIN WM_DB..ATIVOS_BTC B
	ON B.CD_ATIVO = A.CD_ATIVO	

/* Futuros */
INSERT INTO [WM_DB].[dbo].[ATIVOS] (CD_ATIVO, CD_TIPO_ATIVO, NO_ATIVO, CD_CLASSE_ATIVO, CD_ISIN) 
SELECT CD_ATIVO, 'FU',CD_ATIVO, NULL, CD_ISIN
FROM WM_V_UBS_ATIVOS_FU A
WHERE NOT EXISTS (SELECT CD_ATIVO FROM WM_DB..ATIVOS WHERE CD_TIPO_ATIVO = 'FU' AND CD_ATIVO = A.CD_ATIVO)

UPDATE WM_DB..ATIVOS
	SET NO_ATIVO = A.CD_ATIVO,
		CD_CLASSE_ATIVO = A.CD_CLASSE_ATIVO,
		CD_ISIN = A.CD_ISIN
FROM WM_V_UBS_ATIVOS_FU A
INNER JOIN WM_DB..ATIVOS B
	ON B.CD_ATIVO = A.CD_ATIVO 
WHERE B.CD_TIPO_ATIVO = 'FU'
   
INSERT INTO [WM_DB].[dbo].[ATIVOS_FU]
(CD_ATIVO, CD_TIPO_ATIVO ,CD_VENCIMENTO, DT_VENCIMENTO, CD_TIPO_FUT, CD_FUTURO, NU_DIAS_LIQUI)
SELECT CD_ATIVO, CD_TIPO_ATIVO, CD_VENCIMENTO, DT_VENCIMENTO, CD_TIPO_FUT, CD_FUTURO, NU_DIAS_LIQUIDACAO
FROM WM_V_UBS_ATIVOS_FU A
WHERE NOT EXISTS (SELECT CD_ATIVO FROM [WM_DB].[dbo].[ATIVOS_FU] WHERE CD_ATIVO = A.CD_ATIVO)

UPDATE WM_DB..[ATIVOS_FU]
	SET CD_VENCIMENTO = A.CD_VENCIMENTO,
		DT_VENCIMENTO = A.DT_VENCIMENTO, 
		CD_TIPO_FUT = A.CD_TIPO_FUT, 
		CD_FUTURO = A.CD_FUTURO, 
		NU_DIAS_LIQUI =  A.NU_DIAS_LIQUIDACAO
FROM WM_V_UBS_ATIVOS_FU A
INNER JOIN WM_DB..ATIVOS_FU B
	ON B.CD_ATIVO = A.CD_ATIVO	

/* Câmbio */
INSERT INTO [WM_DB].[dbo].[ATIVOS] (CD_ATIVO, CD_TIPO_ATIVO, NO_ATIVO, CD_CLASSE_ATIVO, CD_ISIN)
SELECT  CD_ATIVO, 'CB' AS CD_TIPO_ATIVO, 'NM' AS NO_ATIVO, NULL, CD_ISIN 
FROM WM_V_UBS_ATIVOS_CB A
WHERE NOT EXISTS (SELECT CD_ATIVO FROM [WM_DB].[dbo].[ATIVOS] WHERE CD_TIPO_ATIVO = 'CB' AND CD_ATIVO = A.CD_ATIVO)

INSERT INTO [WM_DB].[dbo].[ATIVOS_CB] 
(CD_ATIVO ,CD_TIPO_ATIVO, CD_MOEDA)
SELECT  CD_ATIVO, CD_TIPO_ATIVO, CD_MOEDA
FROM WM_V_UBS_ATIVOS_CB A
WHERE NOT EXISTS (SELECT CD_ATIVO FROM [WM_DB].[dbo].[ATIVOS_CB] WHERE CD_ATIVO = A.CD_ATIVO)

UPDATE [WM_DB].[dbo].[ATIVOS_CB] 
	SET CD_MOEDA = A.CD_MOEDA
FROM WM_V_UBS_ATIVOS_CB A
INNER JOIN [WM_DB].[dbo].[ATIVOS_CB] B
	ON B.CD_ATIVO = A.CD_ATIVO

/* SWAP */
INSERT INTO [WM_DB].[dbo].[ATIVOS]
           ([CD_ATIVO], [CD_TIPO_ATIVO], NO_ATIVO, CD_CLASSE_ATIVO, CD_ISIN)
SELECT CD_ATIVO, CD_TIPO_ATIVO, NO_ATIVO, CLASSE_ATIVO, CD_ISIN
FROM WM_V_UBS_ATIVOS_SW A
WHERE NOT EXISTS (SELECT CD_ATIVO FROM [WM_DB].[dbo].[ATIVOS] WHERE CD_TIPO_ATIVO = 'SW' AND CD_ATIVO = A.CD_ATIVO )

UPDATE [WM_DB].[dbo].[ATIVOS]
	SET NO_ATIVO = A.NO_ATIVO,
		CD_CLASSE_ATIVO = A.CD_CLASSE_ATIVO,
		CD_ISIN = A.CD_ISIN
FROM WM_V_UBS_ATIVOS_SW A
INNER JOIN [WM_DB].[dbo].[ATIVOS] B
	ON B.CD_ATIVO = A.CD_ATIVO
WHERE B.CD_TIPO_ATIVO = 'SW'	

INSERT INTO [WM_DB].[dbo].[ATIVOS_SW]
           (CD_ATIVO, CD_TIPO_ATIVO, VL_TX_REG, CD_CONTRAPARTE, VL_TAXA_ATIVO, VL_TAXA_PASSIVO, CD_IND_ATIVO, CD_IND_PASSIVO, VL_IND_ATIVO, VL_IND_PASSIVO, MOEDA, DT_INICIO, DT_VENCIMENTO)
SELECT CD_ATIVO, CD_TIPO_ATIVO, VL_TX_REG, CD_CONTRAPARTE, VL_TAXA_ATIVO, VL_TAXA_PASSIVO, CD_IND_ATIVO, CD_IND_PASSIVO, VL_IND_ATIVO, VL_IND_PASSIVO, MOEDA, DT_INICIO, DT_VENCIMENTO
FROM WM_V_UBS_ATIVOS_SW A
WHERE NOT EXISTS (SELECT CD_ATIVO FROM [WM_DB].[dbo].[ATIVOS_SW] WHERE CD_ATIVO = A.CD_ATIVO)

UPDATE [WM_DB].[dbo].[ATIVOS_SW]
	SET VL_TX_REG = A.VL_TX_REG, 
		CD_CONTRAPARTE = A.CD_CONTRAPARTE, 
		VL_TAXA_ATIVO = A.VL_TAXA_ATIVO, 
		VL_TAXA_PASSIVO = A.VL_TAXA_PASSIVO, 
		CD_IND_ATIVO = A.CD_IND_ATIVO, 
		CD_IND_PASSIVO = A.CD_IND_PASSIVO, 
		VL_IND_ATIVO = A.VL_IND_ATIVO, 
		VL_IND_PASSIVO = A.VL_IND_PASSIVO, 
		MOEDA = A.MOEDA, 
		DT_INICIO = A.DT_INICIO, 
		DT_VENCIMENTO = A.DT_VENCIMENTO
FROM WM_V_UBS_ATIVOS_SW A
INNER JOIN [WM_DB].[dbo].[ATIVOS_SW] B
	ON B.CD_ATIVO = A.CD_ATIVO


/* Contas a Pagar/Receber */
INSERT INTO WM_DB..ATIVOS
(CD_ATIVO, CD_TIPO_ATIVO, NO_ATIVO, CD_CLASSE_ATIVO, CD_ISIN)
SELECT CD_ATIVO, 'CP', NO_ATIVO, null, null 
FROM WM_V_UBS_ATIVOS_TE A
WHERE NOT EXISTS (SELECT CD_ATIVO FROM WM_DB..ATIVOS WHERE CD_TIPO_ATIVO = 'CP' AND CD_ATIVO = A.CD_ATIVO)

UPDATE WM_DB..ATIVOS
	SET NO_ATIVO = A.NO_ATIVO
FROM WM_V_UBS_ATIVOS_TE A
INNER JOIN WM_DB..ATIVOS B
	ON B.CD_ATIVO = A.CD_ATIVO
WHERE B.CD_TIPO_ATIVO = 'CP'	

INSERT INTO WM_DB..ATIVOS_CP
(CD_ATIVO, CD_TIPO_ATIVO)
SELECT CD_ATIVO, 'CP'
FROM WM_V_UBS_ATIVOS_TE A
Where NOT EXISTS (SELECT CD_ATIVO FROM WM_DB..ATIVOS_CP WHERE CD_ATIVO = A.CD_ATIVO)
GO

