USE [WM_DB]
GO

/****** Object:  StoredProcedure [dbo].[SP_WMDB_CARGA_DADOS_INSTITUCIONAIS]    Script Date: 08/26/2013 14:13:13 ******/
IF  EXISTS (SELECT * FROM sys.objects WHERE object_id = OBJECT_ID(N'[dbo].[SP_WMDB_CARGA_DADOS_INSTITUCIONAIS]') AND type in (N'P', N'PC'))
DROP PROCEDURE [dbo].[SP_WMDB_CARGA_DADOS_INSTITUCIONAIS]
GO

USE [WM_DB]
GO

/****** Object:  StoredProcedure [dbo].[SP_WMDB_CARGA_DADOS_INSTITUCIONAIS]    Script Date: 08/26/2013 14:13:13 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

Create Procedure [dbo].[SP_WMDB_CARGA_DADOS_INSTITUCIONAIS]
As

Set Nocount On 
/*inserting rows into instituitional tables*/
INSERT INTO [WM_DB].[dbo].[EMPRESA]
           ([CD_EMPRESA]
           ,[NO_EMPRESA])
SELECT 
		BAS_CAD_EMP.CODEMP CD_INST,
       BAS_CAD_EMP.RAZAOSOCIAL NOM_ISTT
  FROM YMF_SAC..BAS_CAD_EMP
WHERE BAS_CAD_EMP.CODEMP NOT IN (SELECT CD_EMPRESA FROM WM_DB..EMPRESA)

INSERT INTO [WM_DB].[dbo].[EMISSOR]
           ([CD_EMISSOR]
           ,[NO_EMISSOR])
SELECT 
	BAS_CAD_IF.CODINST CD_INST,
	BAS_CAD_IF.NOMEINST NOM_ISTT
  FROM YMF_SAC..BAS_CAD_IF
WHERE BAS_CAD_IF.CODINST NOT IN (SELECT CD_EMISSOR FROM [WM_DB].[dbo].EMISSOR)

INSERT INTO [WM_DB].[dbo].[GESTOR]
           ([CD_GESTOR]
           ,[NO_GESTOR])
SELECT 
		SAC_BA_ADMIN.CD CD_INST,
		SAC_BA_ADMIN.NM NOM_ISTT
  FROM YMF_SAC..SAC_BA_ADMIN
WHERE SAC_BA_ADMIN.CD NOT IN (SELECT CD_GESTOR FROM [WM_DB].[dbo].GESTOR)

INSERT INTO [WM_DB].[dbo].[CUSTODIANTE]
           ([CD_CUSTODIANTE]
           ,[NO_CUSTODIANTE])
SELECT 
	BAS_CAD_CONTROL.CD CD_INST,
	BAS_CAD_CONTROL.DESCRICAO NOM_ISTT
  FROM YMF_SAC..BAS_CAD_CONTROL
WHERE BAS_CAD_CONTROL.CD NOT IN (SELECT CD_CUSTODIANTE FROM WM_DB..CUSTODIANTE)

INSERT INTO [WM_DB].[dbo].[ADMINISTRADOR]
           ([CD_ADMINISTRADOR]
           ,[NO_ADMINISTRADOR])
SELECT 
	LTRIM(RTRIM(SAC_BA_ADMINISTRACAO.CD_ADMINISTRACAO)) CD_INST,
	LTRIM(RTRIM(SAC_BA_ADMINISTRACAO.NM_ADMINISTRACAO)) NOM_ISTT
  FROM YMF_SAC..SAC_BA_ADMINISTRACAO 
WHERE LTRIM(RTRIM(SAC_BA_ADMINISTRACAO.CD_ADMINISTRACAO)) NOT IN (SELECT CD_ADMINISTRADOR FROM WM_DB..ADMINISTRADOR)

INSERT INTO [WM_DB]..[CLASSIFICACAO_ATIVOS_FI]
(CD_CLASSIFICACAO, NO_CLASSIFICACAO, CD_TIPO_CLASSIFICACAO)
SELECT DISTINCT ID_TIPO_CLASSIFICACAO, 
	   DS_CLASSIFICACAO, 
	   SG_ORGAO_CLASSIFICADOR 
FROM YMF_SAC..SAC_BA_CLASSIFICACAO_FUNDOS
WHERE ID_TIPO_CLASSIFICACAO NOT IN (SELECT CD_CLASSIFICACAO FROM WM_DB..CLASSIFICACAO_ATIVOS_FI)

INSERT INTO WM_DB..MOEDA
SELECT CODMOEDA, NOMEMOEDA, SIMBOLO, CD_INTERNACIONAL 
	FROM YMF_SAC..BAS_MOEDA
WHERE CODMOEDA NOT IN (SELECT CD_MOEDA FROM WM_DB..MOEDA)
GO

