USE [WM_DB]
GO

/****** Object:  StoredProcedure [dbo].[SP_WMDB_CARGA_MERCADO]    Script Date: 08/26/2013 14:14:00 ******/
IF  EXISTS (SELECT * FROM sys.objects WHERE object_id = OBJECT_ID(N'[dbo].[SP_WMDB_CARGA_MERCADO]') AND type in (N'P', N'PC'))
DROP PROCEDURE [dbo].[SP_WMDB_CARGA_MERCADO]
GO

USE [WM_DB]
GO

/****** Object:  StoredProcedure [dbo].[SP_WMDB_CARGA_MERCADO]    Script Date: 08/26/2013 14:14:00 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

Create Procedure [dbo].[SP_WMDB_CARGA_MERCADO]
As

Set Nocount On 

INSERT WM_DB..MERCADO (CD_MERCADO, NO_MERCADO, IN_ATIVO_INATIVO, CD_USUARIO_ULT_ALT, DT_ULT_ALT)
SELECT COD_MERC, NOM_MERC, 'A', 1,GETDATE() 
FROM YMF_SAC.dbo.SAT_LINK_DM_002
WHERE COD_MERC NOT IN (SELECT CD_MERCADO FROM WM_DB..MERCADO)

INSERT INTO WM_DB..TIPO_ATIVO_MERCADO (CD_TIPO_ATIVO_MERC, NO_TIPO_ATIVO_MERC, CD_MERCADO)
SELECT COD_TIP_ATV, NOM_TIP_ATV, COD_MERC 
FROM YMF_SAC.dbo.SATV_LINK_006
WHERE COD_TIP_ATV NOT IN (SELECT CD_TIPO_ATIVO_MERC FROM WM_DB..TIPO_ATIVO_MERCADO)




GO

