USE [WM_DB]
GO

/****** Object:  StoredProcedure [dbo].[SP_WMDB_CARGA_PERFIL_RISCO]    Script Date: 08/26/2013 14:13:50 ******/
IF  EXISTS (SELECT * FROM sys.objects WHERE object_id = OBJECT_ID(N'[dbo].[SP_WMDB_CARGA_PERFIL_RISCO]') AND type in (N'P', N'PC'))
DROP PROCEDURE [dbo].[SP_WMDB_CARGA_PERFIL_RISCO]
GO

USE [WM_DB]
GO

/****** Object:  StoredProcedure [dbo].[SP_WMDB_CARGA_PERFIL_RISCO]    Script Date: 08/26/2013 14:13:50 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

Create Procedure [dbo].[SP_WMDB_CARGA_PERFIL_RISCO]
As

Set Nocount On 

INSERT INTO WM_DB..PERFIL_RISCO
(CD_PERFIL_RISCO, NO_PERFIL_RISCO, IN_ATIVO_INATIVO)
SELECT DISTINCT CLENQ_CD, CLENQ_CD, 'A'
FROM YMF_SAC..CLI_BAS
WHERE CLENQ_CD IS NOT NULL
  And CLENQ_CD not in (select CD_PERFIL_RISCO from WM_DB..PERFIL_RISCO)
  
UPDATE PERFIL_RISCO
	SET NO_PERFIL_RISCO = A.CLENQ_CD
FROM PERFIL_RISCO B
INNER JOIN YMF_SAC..CLI_BAS A
	ON B.CD_PERFIL_RISCO = A.CLENQ_CD

GO

