USE [WM_DB]
GO

/****** Object:  StoredProcedure [dbo].[SP_WMDB_CARGA_INDEXADORES]    Script Date: 08/26/2013 14:14:10 ******/
IF  EXISTS (SELECT * FROM sys.objects WHERE object_id = OBJECT_ID(N'[dbo].[SP_WMDB_CARGA_INDEXADORES]') AND type in (N'P', N'PC'))
DROP PROCEDURE [dbo].[SP_WMDB_CARGA_INDEXADORES]
GO

USE [WM_DB]
GO

/****** Object:  StoredProcedure [dbo].[SP_WMDB_CARGA_INDEXADORES]    Script Date: 08/26/2013 14:14:10 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

Create Procedure [dbo].[SP_WMDB_CARGA_INDEXADORES]
As

Set Nocount On 

INSERT INTO WM_DB.DBO.INDEXADORES
(CD_INDEXADOR, NM_INDEXADOR, IN_COTA_FUNDO, CD_USUARIO_ULT_ALT, DT_ULT_ALT)
SELECT CODINDEX, NOME, IC_COTA_FUNDO, 1, GETDATE()
FROM YMF_SAC..IDX_INDEXDIR
WHERE CODINDEX NOT IN (SELECT CD_INDEXADOR FROM WM_DB.DBO.INDEXADORES)

update WM_DB.DBO.INDEXADORES
	set NM_INDEXADOR = A.NOME,
	    IN_COTA_FUNDO = A.IC_COTA_FUNDO
FROM YMF_SAC..IDX_INDEXDIR A
INNER JOIN WM_DB.DBO.INDEXADORES B
	ON B.CD_INDEXADOR = A.CODINDEX








GO

