-- USUÁRIO ADMINISTRADOR
INSERT INTO TSYS_PROFILE 
  (ID_PROFILE, 
   DS_NAME, 
   IN_INACTIVE)
VALUES
  (49, 
   'Admin', 
   'N')
  
-- USUÁRIO DE VIZUALIZAÇÃO  
INSERT INTO TSYS_PROFILE 
  (ID_PROFILE, 
   DS_NAME, 
   IN_INACTIVE)
VALUES
  (50, 
   'View',
   'N')  