DECLARE

   ID_PROF NUMBER;
   ID_PROF_APROV NUMBER;   
   ID_PROF_OPER NUMBER;   
   ID_PROF_CONS NUMBER;    

BEGIN

  SELECT ID_PROFILE INTO ID_PROF FROM TSYS_PROFILE WHERE ROWNUM = 1 ORDER BY ID_PROFILE DESC;

  ID_PROF_APROV := ID_PROF + 1;   
  ID_PROF_OPER  := ID_PROF + 2;   
  ID_PROF_CONS  := ID_PROF + 3;   
  
  INSERT INTO TSYS_PROFILE (ID_PROFILE, DS_NAME, IN_INACTIVE) VALUES (ID_PROF_APROV, 'QC_APROVADOR', 'N');        
  INSERT INTO TSYS_PROFILE (ID_PROFILE, DS_NAME, IN_INACTIVE) VALUES (ID_PROF_OPER, 'QC_OPERACIONAL', 'N');   
  INSERT INTO TSYS_PROFILE (ID_PROFILE, DS_NAME, IN_INACTIVE) VALUES (ID_PROF_CONS, 'QC_CONSULTA', 'N');     
     
  INSERT INTO TSYS_MODULE (ID_MODULE, DS_NAME) VALUES ('QUALITYCONTROL', 'QUALITY CONTROL');    
   
END;