// <auto-generated />
namespace abacanet.diamond.infrastructure.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class UserCreation : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(UserCreation));
        
        string IMigrationMetadata.Id
        {
            get { return "201606052253382_UserCreation"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
