// <auto-generated />
namespace abacanet.diamond.infrastructure.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class MappingCreation : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(MappingCreation));
        
        string IMigrationMetadata.Id
        {
            get { return "201606271519368_MappingCreation"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
