// <auto-generated />
namespace audatex.br.audabridge2.infrastructure.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class Operacao : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Operacao));
        
        string IMigrationMetadata.Id
        {
            get { return "201701171306324_Operacao"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
