USE [QUALITY_CONTROL]

DECLARE @DT_REF DATETIME 
SELECT @DT_REF = '2013-05-08'

SELECT DISTINCT
	re.cd_carteira,
	re.CD_TIPO_FILTRO 'CD_TIPO_FILTRO_PAI', 
	re.CD_SUBTIPO_FILTRO 'CD_TIPO_FILTRO', 
	re.IN_ENQUADRADO
FROM 
	RESULTADO_ENQUADRAMENTO re
 	 INNER JOIN TIPO_FILTRO tf ON re.CD_TIPO_FILTRO =  tf.CD_TIPO_FILTRO
	 INNER JOIN TIPO_FILTRO tff ON re.CD_SUBTIPO_FILTRO = tff.CD_TIPO_FILTRO
WHERE	
	tf.IN_ATIVO_INATIVO = 'A' AND
	re.DT_RESULTADO     = @DT_REF AND
	re.CD_PROCESSAMENTO = (select MAX(CD_PROCESSAMENTO) from RESULTADO_ENQUADRAMENTO B where re.CD_CARTEIRA = B.CD_CARTEIRA and re.DT_RESULTADO = B.DT_RESULTADO)
ORDER BY 
	1, 2, 3