--QUERY PARA DESCOBRIR DATA DO PROCESSAMENTO MENSAL DO PERIODO
--SELECT MAX(dt_referencia) 
--FROM PROCESSAMENTO 
--WHERE MONTH(DT_REFERENCIA) = 5 AND YEAR(DT_REFERENCIA) = 2013 
--AND IN_PERIODO_PROCESSAMENTO = 'M'


--QUERY CONSIDERANDO PERIODO MENSAL OU DIARIO
USE [QUALITY_CONTROL]	
	
DECLARE @DT_REF DATETIME 
DECLARE @IN_PERIODO VARCHAR(1)

SELECT @DT_REF = '2013-09-30'	
SELECT @IN_PERIODO = 'D'	

	SELECT DISTINCT 
		TF.CD_CARTEIRA, 
		TF.DT_POSICAO,
		tf.CD_TIPO_FILTRO_PAI, 
		tf.CD_TIPO_FILTRO, 
		--tf.CD_SUBTIPO_FILTRO, 
		tf.CD_PROCESSAMENTO,
		IN_ENQUADRADO 
	FROM 
		(
		SELECT DISTINCT
			re.CD_CARTEIRA, 
			RE.DT_POSICAO,
			f.CD_TIPO_FILTRO, 
			f.CD_TIPO_FILTRO_PAI,	
			re.CD_SUBTIPO_FILTRO,
			RE.CD_PROCESSAMENTO			
		 FROM 
			RESULTADO_ENQUADRAMENTO re 
			INNER JOIN PROCESSAMENTO p ON re.CD_PROCESSAMENTO = p.CD_PROCESSAMENTO
			 FULL JOIN TIPO_FILTRO f ON f.CD_TIPO_FILTRO = f.CD_TIPO_FILTRO
		 WHERE 
			f.CD_TIPO_FILTRO != f.CD_TIPO_FILTRO_PAI AND 
			re.DT_RESULTADO   = @DT_REF           
			AND p.IN_PERIODO_PROCESSAMENTO = @IN_PERIODO AND --('D: DIÁRIO' OU 'M: MENSAL')
			re.CD_PROCESSAMENTO = (select MAX(B.CD_PROCESSAMENTO) from RESULTADO_ENQUADRAMENTO B 
						INNER JOIN PROCESSAMENTO pB ON B.CD_PROCESSAMENTO = pB.CD_PROCESSAMENTO
						where re.CD_CARTEIRA = B.CD_CARTEIRA and re.DT_RESULTADO = B.DT_RESULTADO AND pB.IN_PERIODO_PROCESSAMENTO = @IN_PERIODO)
			AND DT_POSICAO = (SELECT MAX(DT_POSICAO) FROM RESULTADO_ENQUADRAMENTO C 
							INNER JOIN PROCESSAMENTO pC ON C.CD_PROCESSAMENTO = pC.CD_PROCESSAMENTO
							WHERE C.CD_PROCESSAMENTO = re.CD_PROCESSAMENTO AND CD_CARTEIRA = re.CD_CARTEIRA AND pC.IN_PERIODO_PROCESSAMENTO = @IN_PERIODO)
		) tf
	LEFT JOIN 
		(SELECT DISTINCT 
			re.cd_carteira,
			RE.DT_POSICAO,
			re.CD_TIPO_FILTRO 'CD_TIPO_FILTRO_PAI', 
			re.CD_SUBTIPO_FILTRO 'CD_TIPO_FILTRO', 
			RE.CD_PROCESSAMENTO,		
			CASE re.IN_LIBERADO WHEN 'S' THEN 'S' ELSE re.IN_ENQUADRADO END AS IN_ENQUADRADO 	 			 
		 FROM 
			RESULTADO_ENQUADRAMENTO re 
			INNER JOIN PROCESSAMENTO p ON re.CD_PROCESSAMENTO = p.CD_PROCESSAMENTO
		WHERE 
			re.DT_RESULTADO     = @DT_REF
			AND p.IN_PERIODO_PROCESSAMENTO = @IN_PERIODO AND --('D: DIÁRIO' OU 'M: MENSAL')
			re.CD_PROCESSAMENTO = (select MAX(B.CD_PROCESSAMENTO) from RESULTADO_ENQUADRAMENTO B 
						INNER JOIN PROCESSAMENTO pB ON B.CD_PROCESSAMENTO = pB.CD_PROCESSAMENTO
						where re.CD_CARTEIRA = B.CD_CARTEIRA and re.DT_RESULTADO = B.DT_RESULTADO AND pB.IN_PERIODO_PROCESSAMENTO = @IN_PERIODO)
		) res 
		ON tf.CD_TIPO_FILTRO = res.CD_TIPO_FILTRO AND tf.CD_CARTEIRA = res.CD_CARTEIRA 

	ORDER BY 
		 1, 2, 3	
