DECLARE @DT_REF DATETIME 
SELECT @DT_REF = '2013-07-31' 

SELECT 
	ISNULL(TF.NO_TIPO_FILTRO_ABR, TF.NO_TIPO_FILTRO) AS NO_TIPO_FILTRO, 
	TF.CD_TIPO_FILTRO, 
	COUNT(DISTINCT RE.CD_CARTEIRA) AS QTD_CARTEIRAS, 
	SUM(CC.VL_PATRIMONIO) AS VL_PATRIMONIO 
FROM 
	QUALITY_CONTROL..RESULTADO_ENQUADRAMENTO RE 
	INNER JOIN QUALITY_CONTROL..TIPO_FILTRO TF ON 
	RE.CD_SUBTIPO_FILTRO = TF.CD_TIPO_FILTRO 
	LEFT JOIN WM_DB..CARTEIRA_COTA CC ON 
	RE.CD_CARTEIRA = CC.CD_CARTEIRA AND 
	CC.DT_COTA = RE.DT_RESULTADO 
	INNER JOIN QUALITY_CONTROL..PROCESSAMENTO P ON 
	RE.CD_PROCESSAMENTO = P.CD_PROCESSAMENTO 
WHERE 
	RE.DT_RESULTADO        = @DT_REF 
	AND RE.IN_ENQUADRADO   = 'N' 
	AND RE.IN_LIBERADO     = 'N' 
	AND P.CD_PROCESSAMENTO = (SELECT MAX(CD_PROCESSAMENTO) FROM QUALITY_CONTROL..RESULTADO_ENQUADRAMENTO WHERE DT_RESULTADO = @DT_REF AND CD_CARTEIRA = RE.CD_CARTEIRA) 
	AND P.IN_FINALIZADO    = 'S' 
GROUP BY 
	ISNULL(TF.NO_TIPO_FILTRO_ABR, TF.NO_TIPO_FILTRO), 
	TF.CD_TIPO_FILTRO 
ORDER BY 
	TF.CD_TIPO_FILTRO 