// <auto-generated />
namespace audatex.br.centralpublisher.infrastructure.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class OrigemDestino : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(OrigemDestino));
        
        string IMigrationMetadata.Id
        {
            get { return "201611231719295_OrigemDestino"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
