using abacanet.diamond.domain.model;
using abacanet.diamond.domain.model.Mappers;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace abacanet.diamond.domain
{
    public class AFR15Mapper
    {
        public IEnumerable<MapperResponse> Map(ProfitAndLossModel profitAndLoss)
        {
            IEnumerable<COA> coas = GetCoas();

            return BuildValues(profitAndLoss, coas);
        }

        private static IEnumerable<MapperResponse> BuildValues(ProfitAndLossModel profitAndLoss, IEnumerable<COA> coas)
        {
            var responses = new List<MapperResponse>();
            foreach (var coa in coas)
            {
                ProfitAndLossModel project = GetProjects(profitAndLoss, coa);
                if (project == null) continue;

                IList<ProfitAndLossModel> programs = GetPrograms(coa, project);
                IList<ProfitAndLossModel> functions = GetFunctions(coa, programs);
                IList<ProfitAndLossModel> objects = GetObjects(coa, functions);

                responses.Add(new MapperResponse
                {
                    Code = coa.Code,
                    Value = objects.Any(o => o.Children.Any()) ? objects.Sum(o => o.Children.Sum(c => c.Value)) : objects.Sum(o => o.Value)
                });
            }

            return responses;
        }

        private static List<ProfitAndLossModel> GetObjects(COA coa, IList<ProfitAndLossModel> functions)
        {
            var objects = new List<ProfitAndLossModel>();
            foreach (var function in functions)
            {
                objects
                    .AddRange(
                        function.Children
                        .Where(c => coa.Object.Texts.Contains(c.Text) || (c.Number >= coa.Object.InicialNumber && c.Number <= coa.Object.FinalNumber)).ToList());
            }

            return objects;
        }

        private static List<ProfitAndLossModel> GetFunctions(COA coa, IList<ProfitAndLossModel> programs)
        {
            var functions = new List<ProfitAndLossModel>();
            foreach (var program in programs)
            {
                var function = program
                    .Children
                    .Where(c =>
                        (coa.Function.Texts == null || coa.Function.Texts.Contains(c.Text)) ||
                        (coa.Function.Numbers == null || coa.Function.Numbers.Contains(c.Number)))
                    .ToList();

                functions.AddRange(function);
            }

            return functions;
        }

        private static List<ProfitAndLossModel> GetPrograms(COA coa, ProfitAndLossModel project)
        {
            return project.Children
                .Where(c => (coa.Program.Texts != null && coa.Program.Texts.Contains(c.Text)) || coa.Program.Numbers.Contains(c.Number)).ToList();
        }

        private static ProfitAndLossModel GetProjects(ProfitAndLossModel profitAndLoss, COA coa)
        {
            return profitAndLoss.Children
                .Where(c => coa.Project.Texts.Contains(c.Text) || coa.Project.Numbers.Contains(c.Number)).FirstOrDefault();
        }

        #region Datas

        private static IEnumerable<COA> GetCoas()
        {
            var coas = new List<COA>();
            coas.Add(_22());
            coas.Add(_23());
            coas.Add(_24());
            coas.Add(_25());
            coas.Add(_26());
            coas.Add(_27());
            coas.Add(_28());
            coas.Add(_29());
            coas.Add(_30());
            coas.Add(_31());
            coas.Add(_32());
            coas.Add(_33());
            coas.Add(_34());
            coas.Add(_35());
            coas.Add(_36());
            coas.Add(_37());
            coas.Add(_38());
            coas.Add(_39());
            coas.Add(_40());
            coas.Add(_41());
            coas.Add(_42());
            coas.Add(_43());
            coas.Add(_44());
            coas.Add(_45());
            coas.Add(_46());
            coas.Add(_47());
            coas.Add(_48());
            coas.Add(_49());
            coas.Add(_50());
            coas.Add(_51());
            coas.Add(_52());
            coas.Add(_53());
            coas.Add(_54());
            coas.Add(_55());
            coas.Add(_56());
            coas.Add(_57());
            coas.Add(_58());
            coas.Add(_59());
            coas.Add(_60());
            coas.Add(_61());
            coas.Add(_62());
            coas.Add(_63());
            coas.Add(_64());
            coas.Add(_65());
            coas.Add(_66());
            coas.Add(_67());
            coas.Add(_68());
            coas.Add(_69());
            coas.Add(_70());
            coas.Add(_71());
            coas.Add(_72());
            coas.Add(_73());
            coas.Add(_74());
            coas.Add(_75());
            coas.Add(_76());
            coas.Add(_77());
            coas.Add(_78());
            coas.Add(_79());
            coas.Add(_80());
            coas.Add(_81());
            coas.Add(_82());
            coas.Add(_83());
            coas.Add(_84());
            coas.Add(_85());
            coas.Add(_86());
            coas.Add(_87());
            coas.Add(_88());
            coas.Add(_89());
            coas.Add(_90());
            coas.Add(_91());
            coas.Add(_92());
            coas.Add(_93());
            coas.Add(_94());
            coas.Add(_95());
            coas.Add(_96());
            coas.Add(_97());
            coas.Add(_98());
            coas.Add(_99());
            coas.Add(_100());
            coas.Add(_101());
            coas.Add(_102());
            coas.Add(_103());
            coas.Add(_104());
            coas.Add(_105());
            coas.Add(_106());
            coas.Add(_107());
            coas.Add(_108());
            coas.Add(_109());
            coas.Add(_110());
            coas.Add(_111());
            coas.Add(_112());
            coas.Add(_113());
            coas.Add(_114());
            coas.Add(_115());
            coas.Add(_116());
            coas.Add(_117());
            coas.Add(_118());
            coas.Add(_119());
            coas.Add(_120());
            coas.Add(_121());
            coas.Add(_122());
            coas.Add(_123());
            coas.Add(_124());
            coas.Add(_125());
            coas.Add(_126());
            coas.Add(_127());
            coas.Add(_128());
            coas.Add(_129());
            coas.Add(_130());
            coas.Add(_131());
            coas.Add(_132());
            coas.Add(_133());
            coas.Add(_134());
            coas.Add(_135());
            coas.Add(_136());
            coas.Add(_137());
            coas.Add(_138());
            coas.Add(_139());
            coas.Add(_140());
            coas.Add(_141());
            coas.Add(_142());
            coas.Add(_143());
            coas.Add(_144());
            coas.Add(_145());
            coas.Add(_146());
            coas.Add(_147());
            coas.Add(_148());
            coas.Add(_149());
            coas.Add(_150());
            coas.Add(_151());
            coas.Add(_152());
            coas.Add(_153());
            coas.Add(_154());
            coas.Add(_155());
            coas.Add(_156());
            coas.Add(_157());
            coas.Add(_158());
            coas.Add(_159());
            coas.Add(_160());
            coas.Add(_161());
            coas.Add(_162());
            coas.Add(_163());
            coas.Add(_164());
            coas.Add(_165());
            coas.Add(_166());
            coas.Add(_167());
            coas.Add(_168());
            coas.Add(_169());
            coas.Add(_170());
            coas.Add(_171());

            return coas;
        }

        public static COA _22() { var project = new COAItem(); project.Numbers.Add(1000); project.Texts.Add("GENERAL FUND"); project.Texts.Add("Schoolwide Project"); var program = new COAItem(); program.Numbers.Add(100); program.Texts.Add("Regular"); var function = new COAItem(); function.Numbers.Add(1000); function.Texts.Add("Instructional"); var obj = new COARange(); obj.InicialNumber = 6100; obj.FinalNumber = 6199; obj.Texts.Add(" Salaries"); return new COA { Code = 22, Project = project, Program = program, Function = function, Object = obj }; }
        public static COA _23() { var project = new COAItem(); project.Numbers.Add(1000); project.Texts.Add("GENERAL FUND"); project.Texts.Add("Schoolwide Project"); var program = new COAItem(); program.Numbers.Add(100); program.Texts.Add("Regular"); var function = new COAItem(); function.Numbers.Add(1000); function.Texts.Add("Instructional"); var obj = new COARange(); obj.InicialNumber = 6200; obj.FinalNumber = 6299; obj.Texts.Add(" Benefits"); return new COA { Code = 23, Project = project, Program = program, Function = function, Object = obj }; }
        public static COA _24() { var project = new COAItem(); project.Numbers.Add(1000); project.Texts.Add("GENERAL FUND"); project.Texts.Add("Schoolwide Project"); var program = new COAItem(); program.Numbers.Add(100); program.Texts.Add("Regular"); var function = new COAItem(); function.Numbers.Add(1000); function.Texts.Add("Instructional"); var obj = new COARange(); obj.InicialNumber = 6300; obj.FinalNumber = 6599; obj.Texts.Add(" Purchased Services"); return new COA { Code = 24, Project = project, Program = program, Function = function, Object = obj }; }
        public static COA _25() { var project = new COAItem(); project.Numbers.Add(1000); project.Texts.Add("GENERAL FUND"); project.Texts.Add("Schoolwide Project"); var program = new COAItem(); program.Numbers.Add(100); program.Texts.Add("Regular"); var function = new COAItem(); function.Numbers.Add(1000); function.Texts.Add("Instructional"); var obj = new COARange(); obj.InicialNumber = 6600; obj.FinalNumber = 6699; obj.Texts.Add(" Supplies"); return new COA { Code = 25, Project = project, Program = program, Function = function, Object = obj }; }
        public static COA _26() { var project = new COAItem(); project.Numbers.Add(1000); project.Texts.Add("GENERAL FUND"); project.Texts.Add("Schoolwide Project"); var program = new COAItem(); program.Numbers.Add(100); program.Texts.Add("Regular"); var function = new COAItem(); function.Numbers.Add(1000); function.Texts.Add("Instructional"); var obj = new COARange(); obj.InicialNumber = 6800; obj.FinalNumber = 6899; obj.Texts.Add(" Other"); return new COA { Code = 26, Project = project, Program = program, Function = function, Object = obj }; }
        public static COA _27() { var project = new COAItem(); project.Numbers.Add(1000); project.Texts.Add("GENERAL FUND"); project.Texts.Add("Schoolwide Project"); var program = new COAItem(); program.Numbers.Add(100); program.Texts.Add("Regular"); var function = new COAItem(); function.Numbers.Add(2100); function.Texts.Add("Student Support"); var obj = new COARange(); obj.InicialNumber = 6100; obj.FinalNumber = 6199; obj.Texts.Add(" Salaries"); return new COA { Code = 27, Project = project, Program = program, Function = function, Object = obj }; }
        public static COA _28() { var project = new COAItem(); project.Numbers.Add(1000); project.Texts.Add("GENERAL FUND"); project.Texts.Add("Schoolwide Project"); var program = new COAItem(); program.Numbers.Add(100); program.Texts.Add("Regular"); var function = new COAItem(); function.Numbers.Add(2100); function.Texts.Add("Student Support"); var obj = new COARange(); obj.InicialNumber = 6200; obj.FinalNumber = 6299; obj.Texts.Add(" Benefits"); return new COA { Code = 28, Project = project, Program = program, Function = function, Object = obj }; }
        public static COA _29() { var project = new COAItem(); project.Numbers.Add(1000); project.Texts.Add("GENERAL FUND"); project.Texts.Add("Schoolwide Project"); var program = new COAItem(); program.Numbers.Add(100); program.Texts.Add("Regular"); var function = new COAItem(); function.Numbers.Add(2100); function.Texts.Add("Student Support"); var obj = new COARange(); obj.InicialNumber = 6300; obj.FinalNumber = 6599; obj.Texts.Add(" Purchased Services"); return new COA { Code = 29, Project = project, Program = program, Function = function, Object = obj }; }
        public static COA _30() { var project = new COAItem(); project.Numbers.Add(1000); project.Texts.Add("GENERAL FUND"); project.Texts.Add("Schoolwide Project"); var program = new COAItem(); program.Numbers.Add(100); program.Texts.Add("Regular"); var function = new COAItem(); function.Numbers.Add(2100); function.Texts.Add("Student Support"); var obj = new COARange(); obj.InicialNumber = 6600; obj.FinalNumber = 6699; obj.Texts.Add(" Supplies"); return new COA { Code = 30, Project = project, Program = program, Function = function, Object = obj }; }
        public static COA _31() { var project = new COAItem(); project.Numbers.Add(1000); project.Texts.Add("GENERAL FUND"); project.Texts.Add("Schoolwide Project"); var program = new COAItem(); program.Numbers.Add(100); program.Texts.Add("Regular"); var function = new COAItem(); function.Numbers.Add(2100); function.Texts.Add("Student Support"); var obj = new COARange(); obj.InicialNumber = 6800; obj.FinalNumber = 6899; obj.Texts.Add(" Other"); return new COA { Code = 31, Project = project, Program = program, Function = function, Object = obj }; }
        public static COA _32() { var project = new COAItem(); project.Numbers.Add(1000); project.Texts.Add("GENERAL FUND"); project.Texts.Add("Schoolwide Project"); var program = new COAItem(); program.Numbers.Add(100); program.Texts.Add("Regular"); var function = new COAItem(); function.Numbers.Add(2200); function.Texts.Add("Teacher Support"); var obj = new COARange(); obj.InicialNumber = 6100; obj.FinalNumber = 6199; obj.Texts.Add(" Salaries"); return new COA { Code = 32, Project = project, Program = program, Function = function, Object = obj }; }
        public static COA _33() { var project = new COAItem(); project.Numbers.Add(1000); project.Texts.Add("GENERAL FUND"); project.Texts.Add("Schoolwide Project"); var program = new COAItem(); program.Numbers.Add(100); program.Texts.Add("Regular"); var function = new COAItem(); function.Numbers.Add(2200); function.Texts.Add("Teacher Support"); var obj = new COARange(); obj.InicialNumber = 6200; obj.FinalNumber = 6299; obj.Texts.Add(" Benefits"); return new COA { Code = 33, Project = project, Program = program, Function = function, Object = obj }; }
        public static COA _34() { var project = new COAItem(); project.Numbers.Add(1000); project.Texts.Add("GENERAL FUND"); project.Texts.Add("Schoolwide Project"); var program = new COAItem(); program.Numbers.Add(100); program.Texts.Add("Regular"); var function = new COAItem(); function.Numbers.Add(2200); function.Texts.Add("Teacher Support"); var obj = new COARange(); obj.InicialNumber = 6300; obj.FinalNumber = 6599; obj.Texts.Add(" Purchased Services"); return new COA { Code = 34, Project = project, Program = program, Function = function, Object = obj }; }
        public static COA _35() { var project = new COAItem(); project.Numbers.Add(1000); project.Texts.Add("GENERAL FUND"); project.Texts.Add("Schoolwide Project"); var program = new COAItem(); program.Numbers.Add(100); program.Texts.Add("Regular"); var function = new COAItem(); function.Numbers.Add(2200); function.Texts.Add("Teacher Support"); var obj = new COARange(); obj.InicialNumber = 6600; obj.FinalNumber = 6699; obj.Texts.Add(" Supplies"); return new COA { Code = 35, Project = project, Program = program, Function = function, Object = obj }; }
        public static COA _36() { var project = new COAItem(); project.Numbers.Add(1000); project.Texts.Add("GENERAL FUND"); project.Texts.Add("Schoolwide Project"); var program = new COAItem(); program.Numbers.Add(100); program.Texts.Add("Regular"); var function = new COAItem(); function.Numbers.Add(2200); function.Texts.Add("Teacher Support"); var obj = new COARange(); obj.InicialNumber = 6800; obj.FinalNumber = 6899; obj.Texts.Add(" Other"); return new COA { Code = 36, Project = project, Program = program, Function = function, Object = obj }; }
        public static COA _37() { var project = new COAItem(); project.Numbers.Add(1000); project.Texts.Add("GENERAL FUND"); project.Texts.Add("Schoolwide Project"); var program = new COAItem(); program.Numbers.Add(100); program.Texts.Add("Regular"); var function = new COAItem(); function.Numbers.Add(2300); function.Texts.Add("General Administration"); var obj = new COARange(); obj.InicialNumber = 6100; obj.FinalNumber = 6199; obj.Texts.Add(" Salaries"); return new COA { Code = 37, Project = project, Program = program, Function = function, Object = obj }; }
        public static COA _38() { var project = new COAItem(); project.Numbers.Add(1000); project.Texts.Add("GENERAL FUND"); project.Texts.Add("Schoolwide Project"); var program = new COAItem(); program.Numbers.Add(100); program.Texts.Add("Regular"); var function = new COAItem(); function.Numbers.Add(2300); function.Texts.Add("General Administration"); var obj = new COARange(); obj.InicialNumber = 6200; obj.FinalNumber = 6299; obj.Texts.Add(" Benefits"); return new COA { Code = 38, Project = project, Program = program, Function = function, Object = obj }; }
        public static COA _39() { var project = new COAItem(); project.Numbers.Add(1000); project.Texts.Add("GENERAL FUND"); project.Texts.Add("Schoolwide Project"); var program = new COAItem(); program.Numbers.Add(100); program.Texts.Add("Regular"); var function = new COAItem(); function.Numbers.Add(2300); function.Texts.Add("General Administration"); var obj = new COARange(); obj.InicialNumber = 6300; obj.FinalNumber = 6599; obj.Texts.Add(" Purchased Services"); return new COA { Code = 39, Project = project, Program = program, Function = function, Object = obj }; }
        public static COA _40() { var project = new COAItem(); project.Numbers.Add(1000); project.Texts.Add("GENERAL FUND"); project.Texts.Add("Schoolwide Project"); var program = new COAItem(); program.Numbers.Add(100); program.Texts.Add("Regular"); var function = new COAItem(); function.Numbers.Add(2300); function.Texts.Add("General Administration"); var obj = new COARange(); obj.InicialNumber = 6600; obj.FinalNumber = 6699; obj.Texts.Add(" Supplies"); return new COA { Code = 40, Project = project, Program = program, Function = function, Object = obj }; }
        public static COA _41() { var project = new COAItem(); project.Numbers.Add(1000); project.Texts.Add("GENERAL FUND"); project.Texts.Add("Schoolwide Project"); var program = new COAItem(); program.Numbers.Add(100); program.Texts.Add("Regular"); var function = new COAItem(); function.Numbers.Add(2300); function.Texts.Add("General Administration"); var obj = new COARange(); obj.InicialNumber = 6800; obj.FinalNumber = 6899; obj.Texts.Add(" Other"); return new COA { Code = 41, Project = project, Program = program, Function = function, Object = obj }; }
        public static COA _42() { var project = new COAItem(); project.Numbers.Add(1000); project.Texts.Add("GENERAL FUND"); project.Texts.Add("Schoolwide Project"); var program = new COAItem(); program.Numbers.Add(100); program.Texts.Add("Regular"); var function = new COAItem(); function.Numbers.Add(2400); function.Texts.Add("School Administration"); var obj = new COARange(); obj.InicialNumber = 6100; obj.FinalNumber = 6199; obj.Texts.Add(" Salaries"); return new COA { Code = 42, Project = project, Program = program, Function = function, Object = obj }; }
        public static COA _43() { var project = new COAItem(); project.Numbers.Add(1000); project.Texts.Add("GENERAL FUND"); project.Texts.Add("Schoolwide Project"); var program = new COAItem(); program.Numbers.Add(100); program.Texts.Add("Regular"); var function = new COAItem(); function.Numbers.Add(2400); function.Texts.Add("School Administration"); var obj = new COARange(); obj.InicialNumber = 6200; obj.FinalNumber = 6299; obj.Texts.Add(" Benefits"); return new COA { Code = 43, Project = project, Program = program, Function = function, Object = obj }; }
        public static COA _44() { var project = new COAItem(); project.Numbers.Add(1000); project.Texts.Add("GENERAL FUND"); project.Texts.Add("Schoolwide Project"); var program = new COAItem(); program.Numbers.Add(100); program.Texts.Add("Regular"); var function = new COAItem(); function.Numbers.Add(2400); function.Texts.Add("School Administration"); var obj = new COARange(); obj.InicialNumber = 6300; obj.FinalNumber = 6599; obj.Texts.Add(" Purchased Services"); return new COA { Code = 44, Project = project, Program = program, Function = function, Object = obj }; }
        public static COA _45() { var project = new COAItem(); project.Numbers.Add(1000); project.Texts.Add("GENERAL FUND"); project.Texts.Add("Schoolwide Project"); var program = new COAItem(); program.Numbers.Add(100); program.Texts.Add("Regular"); var function = new COAItem(); function.Numbers.Add(2400); function.Texts.Add("School Administration"); var obj = new COARange(); obj.InicialNumber = 6600; obj.FinalNumber = 6699; obj.Texts.Add(" Supplies"); return new COA { Code = 45, Project = project, Program = program, Function = function, Object = obj }; }
        public static COA _46() { var project = new COAItem(); project.Numbers.Add(1000); project.Texts.Add("GENERAL FUND"); project.Texts.Add("Schoolwide Project"); var program = new COAItem(); program.Numbers.Add(100); program.Texts.Add("Regular"); var function = new COAItem(); function.Numbers.Add(2400); function.Texts.Add("School Administration"); var obj = new COARange(); obj.InicialNumber = 6800; obj.FinalNumber = 6899; obj.Texts.Add(" Other"); return new COA { Code = 46, Project = project, Program = program, Function = function, Object = obj }; }
        public static COA _47() { var project = new COAItem(); project.Numbers.Add(1000); project.Texts.Add("GENERAL FUND"); project.Texts.Add("Schoolwide Project"); var program = new COAItem(); program.Numbers.Add(100); program.Texts.Add("Regular"); var function = new COAItem(); function.Numbers.Add(2500); function.Texts.Add("Central Services"); var obj = new COARange(); obj.InicialNumber = 6100; obj.FinalNumber = 6199; obj.Texts.Add(" Salaries"); return new COA { Code = 47, Project = project, Program = program, Function = function, Object = obj }; }
        public static COA _48() { var project = new COAItem(); project.Numbers.Add(1000); project.Texts.Add("GENERAL FUND"); project.Texts.Add("Schoolwide Project"); var program = new COAItem(); program.Numbers.Add(100); program.Texts.Add("Regular"); var function = new COAItem(); function.Numbers.Add(2500); function.Texts.Add("Central Services"); var obj = new COARange(); obj.InicialNumber = 6200; obj.FinalNumber = 6299; obj.Texts.Add(" Benefits"); return new COA { Code = 48, Project = project, Program = program, Function = function, Object = obj }; }
        public static COA _49() { var project = new COAItem(); project.Numbers.Add(1000); project.Texts.Add("GENERAL FUND"); project.Texts.Add("Schoolwide Project"); var program = new COAItem(); program.Numbers.Add(100); program.Texts.Add("Regular"); var function = new COAItem(); function.Numbers.Add(2500); function.Texts.Add("Central Services"); var obj = new COARange(); obj.InicialNumber = 6300; obj.FinalNumber = 6599; obj.Texts.Add(" Purchased Services"); return new COA { Code = 49, Project = project, Program = program, Function = function, Object = obj }; }
        public static COA _50() { var project = new COAItem(); project.Numbers.Add(1000); project.Texts.Add("GENERAL FUND"); project.Texts.Add("Schoolwide Project"); var program = new COAItem(); program.Numbers.Add(100); program.Texts.Add("Regular"); var function = new COAItem(); function.Numbers.Add(2500); function.Texts.Add("Central Services"); var obj = new COARange(); obj.InicialNumber = 6600; obj.FinalNumber = 6699; obj.Texts.Add(" Supplies"); return new COA { Code = 50, Project = project, Program = program, Function = function, Object = obj }; }
        public static COA _51() { var project = new COAItem(); project.Numbers.Add(1000); project.Texts.Add("GENERAL FUND"); project.Texts.Add("Schoolwide Project"); var program = new COAItem(); program.Numbers.Add(100); program.Texts.Add("Regular"); var function = new COAItem(); function.Numbers.Add(2500); function.Texts.Add("Central Services"); var obj = new COARange(); obj.InicialNumber = 6800; obj.FinalNumber = 6899; obj.Texts.Add(" Other"); return new COA { Code = 51, Project = project, Program = program, Function = function, Object = obj }; }
        public static COA _52() { var project = new COAItem(); project.Numbers.Add(1000); project.Texts.Add("GENERAL FUND"); project.Texts.Add("Schoolwide Project"); var program = new COAItem(); program.Numbers.Add(100); program.Texts.Add("Regular"); var function = new COAItem(); function.Numbers.Add(2600); function.Texts.Add(" Plant or Facility"); var obj = new COARange(); obj.InicialNumber = 6100; obj.FinalNumber = 6199; obj.Texts.Add(" Salaries"); return new COA { Code = 52, Project = project, Program = program, Function = function, Object = obj }; }
        public static COA _53() { var project = new COAItem(); project.Numbers.Add(1000); project.Texts.Add("GENERAL FUND"); project.Texts.Add("Schoolwide Project"); var program = new COAItem(); program.Numbers.Add(100); program.Texts.Add("Regular"); var function = new COAItem(); function.Numbers.Add(2600); function.Texts.Add(" Plant or Facility"); var obj = new COARange(); obj.InicialNumber = 6200; obj.FinalNumber = 6299; obj.Texts.Add(" Benefits"); return new COA { Code = 53, Project = project, Program = program, Function = function, Object = obj }; }
        public static COA _54() { var project = new COAItem(); project.Numbers.Add(1000); project.Texts.Add("GENERAL FUND"); project.Texts.Add("Schoolwide Project"); var program = new COAItem(); program.Numbers.Add(100); program.Texts.Add("Regular"); var function = new COAItem(); function.Numbers.Add(2600); function.Texts.Add(" Plant or Facility"); var obj = new COARange(); obj.InicialNumber = 6300; obj.FinalNumber = 6599; obj.Texts.Add(" Purchased Services"); return new COA { Code = 54, Project = project, Program = program, Function = function, Object = obj }; }
        public static COA _55() { var project = new COAItem(); project.Numbers.Add(1000); project.Texts.Add("GENERAL FUND"); project.Texts.Add("Schoolwide Project"); var program = new COAItem(); program.Numbers.Add(100); program.Texts.Add("Regular"); var function = new COAItem(); function.Numbers.Add(2600); function.Texts.Add(" Plant or Facility"); var obj = new COARange(); obj.InicialNumber = 6600; obj.FinalNumber = 6699; obj.Texts.Add(" Supplies"); return new COA { Code = 55, Project = project, Program = program, Function = function, Object = obj }; }
        public static COA _56() { var project = new COAItem(); project.Numbers.Add(1000); project.Texts.Add("GENERAL FUND"); project.Texts.Add("Schoolwide Project"); var program = new COAItem(); program.Numbers.Add(100); program.Texts.Add("Regular"); var function = new COAItem(); function.Numbers.Add(2600); function.Texts.Add(" Plant or Facility"); var obj = new COARange(); obj.InicialNumber = 6800; obj.FinalNumber = 6899; obj.Texts.Add(" Other"); return new COA { Code = 56, Project = project, Program = program, Function = function, Object = obj }; }
        public static COA _57() { var project = new COAItem(); project.Numbers.Add(1000); project.Texts.Add("GENERAL FUND"); project.Texts.Add("Schoolwide Project"); var program = new COAItem(); program.Numbers.Add(100); program.Texts.Add("Regular"); var function = new COAItem(); function.Numbers.Add(2900); function.Texts.Add("Other"); var obj = new COARange(); obj.InicialNumber = 6100; obj.FinalNumber = 6199; obj.Texts.Add(" Salaries"); return new COA { Code = 57, Project = project, Program = program, Function = function, Object = obj }; }
        public static COA _58() { var project = new COAItem(); project.Numbers.Add(1000); project.Texts.Add("GENERAL FUND"); project.Texts.Add("Schoolwide Project"); var program = new COAItem(); program.Numbers.Add(100); program.Texts.Add("Regular"); var function = new COAItem(); function.Numbers.Add(2900); function.Texts.Add("Other"); var obj = new COARange(); obj.InicialNumber = 6200; obj.FinalNumber = 6299; obj.Texts.Add(" Benefits"); return new COA { Code = 58, Project = project, Program = program, Function = function, Object = obj }; }
        public static COA _59() { var project = new COAItem(); project.Numbers.Add(1000); project.Texts.Add("GENERAL FUND"); project.Texts.Add("Schoolwide Project"); var program = new COAItem(); program.Numbers.Add(100); program.Texts.Add("Regular"); var function = new COAItem(); function.Numbers.Add(2900); function.Texts.Add("Other"); var obj = new COARange(); obj.InicialNumber = 6300; obj.FinalNumber = 6599; obj.Texts.Add(" Purchased Services"); return new COA { Code = 59, Project = project, Program = program, Function = function, Object = obj }; }
        public static COA _60() { var project = new COAItem(); project.Numbers.Add(1000); project.Texts.Add("GENERAL FUND"); project.Texts.Add("Schoolwide Project"); var program = new COAItem(); program.Numbers.Add(100); program.Texts.Add("Regular"); var function = new COAItem(); function.Numbers.Add(2900); function.Texts.Add("Other"); var obj = new COARange(); obj.InicialNumber = 6600; obj.FinalNumber = 6699; obj.Texts.Add(" Supplies"); return new COA { Code = 60, Project = project, Program = program, Function = function, Object = obj }; }
        public static COA _61() { var project = new COAItem(); project.Numbers.Add(1000); project.Texts.Add("GENERAL FUND"); project.Texts.Add("Schoolwide Project"); var program = new COAItem(); program.Numbers.Add(100); program.Texts.Add("Regular"); var function = new COAItem(); function.Numbers.Add(2900); function.Texts.Add("Other"); var obj = new COARange(); obj.InicialNumber = 6800; obj.FinalNumber = 6899; obj.Texts.Add(" Other"); return new COA { Code = 61, Project = project, Program = program, Function = function, Object = obj }; }
        public static COA _62() { var project = new COAItem(); project.Numbers.Add(1000); project.Texts.Add("GENERAL FUND"); project.Texts.Add("Schoolwide Project"); var program = new COAItem(); program.Numbers.Add(100); program.Texts.Add("Regular"); var function = new COAItem(); function.Numbers.Add(3000); function.Texts.Add("9 or Noninstructional "); var obj = new COARange(); obj.InicialNumber = 6100; obj.FinalNumber = 6199; obj.Texts.Add(" Salaries"); return new COA { Code = 62, Project = project, Program = program, Function = function, Object = obj }; }
        public static COA _63() { var project = new COAItem(); project.Numbers.Add(1000); project.Texts.Add("GENERAL FUND"); project.Texts.Add("Schoolwide Project"); var program = new COAItem(); program.Numbers.Add(100); program.Texts.Add("Regular"); var function = new COAItem(); function.Numbers.Add(3000); function.Texts.Add("9 or Noninstructional "); var obj = new COARange(); obj.InicialNumber = 6200; obj.FinalNumber = 6299; obj.Texts.Add(" Benefits"); return new COA { Code = 63, Project = project, Program = program, Function = function, Object = obj }; }
        public static COA _64() { var project = new COAItem(); project.Numbers.Add(1000); project.Texts.Add("GENERAL FUND"); project.Texts.Add("Schoolwide Project"); var program = new COAItem(); program.Numbers.Add(100); program.Texts.Add("Regular"); var function = new COAItem(); function.Numbers.Add(3000); function.Texts.Add("9 or Noninstructional "); var obj = new COARange(); obj.InicialNumber = 6300; obj.FinalNumber = 6599; obj.Texts.Add(" Purchased Services"); return new COA { Code = 64, Project = project, Program = program, Function = function, Object = obj }; }
        public static COA _65() { var project = new COAItem(); project.Numbers.Add(1000); project.Texts.Add("GENERAL FUND"); project.Texts.Add("Schoolwide Project"); var program = new COAItem(); program.Numbers.Add(100); program.Texts.Add("Regular"); var function = new COAItem(); function.Numbers.Add(3000); function.Texts.Add("9 or Noninstructional "); var obj = new COARange(); obj.InicialNumber = 6600; obj.FinalNumber = 6699; obj.Texts.Add(" Supplies"); return new COA { Code = 65, Project = project, Program = program, Function = function, Object = obj }; }
        public static COA _66() { var project = new COAItem(); project.Numbers.Add(1000); project.Texts.Add("GENERAL FUND"); project.Texts.Add("Schoolwide Project"); var program = new COAItem(); program.Numbers.Add(100); program.Texts.Add("Regular"); var function = new COAItem(); function.Numbers.Add(3000); function.Texts.Add("9 or Noninstructional "); var obj = new COARange(); obj.InicialNumber = 6800; obj.FinalNumber = 6899; obj.Texts.Add(" Other"); return new COA { Code = 66, Project = project, Program = program, Function = function, Object = obj }; }
        public static COA _67() { var project = new COAItem(); project.Numbers.Add(1000); project.Texts.Add("GENERAL FUND"); project.Texts.Add("Schoolwide Project"); var program = new COAItem(); program.Numbers.Add(100); program.Texts.Add("Regular"); var function = new COAItem(); function.Numbers.Add(4000); function.Texts.Add("Facility Acquisition"); var obj = new COARange(); obj.InicialNumber = 6100; obj.FinalNumber = 6199; obj.Texts.Add(" Salaries"); return new COA { Code = 67, Project = project, Program = program, Function = function, Object = obj }; }
        public static COA _68() { var project = new COAItem(); project.Numbers.Add(1000); project.Texts.Add("GENERAL FUND"); project.Texts.Add("Schoolwide Project"); var program = new COAItem(); program.Numbers.Add(100); program.Texts.Add("Regular"); var function = new COAItem(); function.Numbers.Add(4000); function.Texts.Add("Facility Acquisition"); var obj = new COARange(); obj.InicialNumber = 6200; obj.FinalNumber = 6299; obj.Texts.Add(" Benefits"); return new COA { Code = 68, Project = project, Program = program, Function = function, Object = obj }; }
        public static COA _69() { var project = new COAItem(); project.Numbers.Add(1000); project.Texts.Add("GENERAL FUND"); project.Texts.Add("Schoolwide Project"); var program = new COAItem(); program.Numbers.Add(100); program.Texts.Add("Regular"); var function = new COAItem(); function.Numbers.Add(4000); function.Texts.Add("Facility Acquisition"); var obj = new COARange(); obj.InicialNumber = 6300; obj.FinalNumber = 6599; obj.Texts.Add(" Purchased Services"); return new COA { Code = 69, Project = project, Program = program, Function = function, Object = obj }; }
        public static COA _70() { var project = new COAItem(); project.Numbers.Add(1000); project.Texts.Add("GENERAL FUND"); project.Texts.Add("Schoolwide Project"); var program = new COAItem(); program.Numbers.Add(100); program.Texts.Add("Regular"); var function = new COAItem(); function.Numbers.Add(4000); function.Texts.Add("Facility Acquisition"); var obj = new COARange(); obj.InicialNumber = 6600; obj.FinalNumber = 6699; obj.Texts.Add(" Supplies"); return new COA { Code = 70, Project = project, Program = program, Function = function, Object = obj }; }
        public static COA _71() { var project = new COAItem(); project.Numbers.Add(1000); project.Texts.Add("GENERAL FUND"); project.Texts.Add("Schoolwide Project"); var program = new COAItem(); program.Numbers.Add(100); program.Texts.Add("Regular"); var function = new COAItem(); function.Numbers.Add(4000); function.Texts.Add("Facility Acquisition"); var obj = new COARange(); obj.InicialNumber = 6800; obj.FinalNumber = 6899; obj.Texts.Add(" Other"); return new COA { Code = 71, Project = project, Program = program, Function = function, Object = obj }; }
        public static COA _72() { var project = new COAItem(); project.Numbers.Add(1000); project.Texts.Add("GENERAL FUND"); project.Texts.Add("Schoolwide Project"); var program = new COAItem(); program.Numbers.Add(100); program.Texts.Add("Regular"); var function = new COAItem(); function.Numbers.Add(5000); function.Texts.Add("Debt Service"); var obj = new COARange(); obj.InicialNumber = 6100; obj.FinalNumber = 6199; obj.Texts.Add(" Salaries"); return new COA { Code = 72, Project = project, Program = program, Function = function, Object = obj }; }
        public static COA _73() { var project = new COAItem(); project.Numbers.Add(1000); project.Texts.Add("GENERAL FUND"); project.Texts.Add("Schoolwide Project"); var program = new COAItem(); program.Numbers.Add(100); program.Texts.Add("Regular"); var function = new COAItem(); function.Numbers.Add(5000); function.Texts.Add("Debt Service"); var obj = new COARange(); obj.InicialNumber = 6200; obj.FinalNumber = 6299; obj.Texts.Add(" Benefits"); return new COA { Code = 73, Project = project, Program = program, Function = function, Object = obj }; }
        public static COA _74() { var project = new COAItem(); project.Numbers.Add(1000); project.Texts.Add("GENERAL FUND"); project.Texts.Add("Schoolwide Project"); var program = new COAItem(); program.Numbers.Add(100); program.Texts.Add("Regular"); var function = new COAItem(); function.Numbers.Add(5000); function.Texts.Add("Debt Service"); var obj = new COARange(); obj.InicialNumber = 6300; obj.FinalNumber = 6599; obj.Texts.Add(" Purchased Services"); return new COA { Code = 74, Project = project, Program = program, Function = function, Object = obj }; }
        public static COA _75() { var project = new COAItem(); project.Numbers.Add(1000); project.Texts.Add("GENERAL FUND"); project.Texts.Add("Schoolwide Project"); var program = new COAItem(); program.Numbers.Add(100); program.Texts.Add("Regular"); var function = new COAItem(); function.Numbers.Add(5000); function.Texts.Add("Debt Service"); var obj = new COARange(); obj.InicialNumber = 6600; obj.FinalNumber = 6699; obj.Texts.Add(" Supplies"); return new COA { Code = 75, Project = project, Program = program, Function = function, Object = obj }; }
        public static COA _76() { var project = new COAItem(); project.Numbers.Add(1000); project.Texts.Add("GENERAL FUND"); project.Texts.Add("Schoolwide Project"); var program = new COAItem(); program.Numbers.Add(100); program.Texts.Add("Regular"); var function = new COAItem(); function.Numbers.Add(5000); function.Texts.Add("Debt Service"); var obj = new COARange(); obj.InicialNumber = 6800; obj.FinalNumber = 6899; obj.Texts.Add(" Other"); return new COA { Code = 76, Project = project, Program = program, Function = function, Object = obj }; }
        public static COA _77() { var project = new COAItem(); project.Numbers.Add(1000); project.Texts.Add("GENERAL FUND"); project.Texts.Add("Schoolwide Project"); var program = new COAItem(); program.Numbers.Add(610); program.Texts.Add("Extracurricular activities"); var function = new COAItem(); function.Numbers = null; function.Texts = null; var obj = new COARange(); obj.InicialNumber = 6100; obj.FinalNumber = 6199; obj.Texts.Add(" Salaries"); return new COA { Code = 77, Project = project, Program = program, Function = function, Object = obj }; }
        public static COA _78() { var project = new COAItem(); project.Numbers.Add(1000); project.Texts.Add("GENERAL FUND"); project.Texts.Add("Schoolwide Project"); var program = new COAItem(); program.Numbers.Add(610); program.Texts.Add("Extracurricular activities"); var function = new COAItem(); function.Numbers = null; function.Texts = null; var obj = new COARange(); obj.InicialNumber = 6200; obj.FinalNumber = 6299; obj.Texts.Add(" Benefits"); return new COA { Code = 78, Project = project, Program = program, Function = function, Object = obj }; }
        public static COA _79() { var project = new COAItem(); project.Numbers.Add(1000); project.Texts.Add("GENERAL FUND"); project.Texts.Add("Schoolwide Project"); var program = new COAItem(); program.Numbers.Add(610); program.Texts.Add("Extracurricular activities"); var function = new COAItem(); function.Numbers = null; function.Texts = null; var obj = new COARange(); obj.InicialNumber = 6300; obj.FinalNumber = 6599; obj.Texts.Add(" Purchased Services"); return new COA { Code = 79, Project = project, Program = program, Function = function, Object = obj }; }
        public static COA _80() { var project = new COAItem(); project.Numbers.Add(1000); project.Texts.Add("GENERAL FUND"); project.Texts.Add("Schoolwide Project"); var program = new COAItem(); program.Numbers.Add(610); program.Texts.Add("Extracurricular activities"); var function = new COAItem(); function.Numbers = null; function.Texts = null; var obj = new COARange(); obj.InicialNumber = 6600; obj.FinalNumber = 6699; obj.Texts.Add(" Supplies"); return new COA { Code = 80, Project = project, Program = program, Function = function, Object = obj }; }
        public static COA _81() { var project = new COAItem(); project.Numbers.Add(1000); project.Texts.Add("GENERAL FUND"); project.Texts.Add("Schoolwide Project"); var program = new COAItem(); program.Numbers.Add(610); program.Texts.Add("Extracurricular activities"); var function = new COAItem(); function.Numbers = null; function.Texts = null; var obj = new COARange(); obj.InicialNumber = 6800; obj.FinalNumber = 6899; obj.Texts.Add(" Other"); return new COA { Code = 81, Project = project, Program = program, Function = function, Object = obj }; }
        public static COA _82() { var project = new COAItem(); project.Numbers.Add(1000); project.Texts.Add("GENERAL FUND"); project.Texts.Add("Schoolwide Project"); var program = new COAItem(); program.Numbers.Add(620); program.Texts.Add("Athletics"); var function = new COAItem(); function.Numbers = null; function.Texts = null; var obj = new COARange(); obj.InicialNumber = 6100; obj.FinalNumber = 6199; obj.Texts.Add(" Salaries"); return new COA { Code = 82, Project = project, Program = program, Function = function, Object = obj }; }
        public static COA _83() { var project = new COAItem(); project.Numbers.Add(1000); project.Texts.Add("GENERAL FUND"); project.Texts.Add("Schoolwide Project"); var program = new COAItem(); program.Numbers.Add(620); program.Texts.Add("Athletics"); var function = new COAItem(); function.Numbers = null; function.Texts = null; var obj = new COARange(); obj.InicialNumber = 6200; obj.FinalNumber = 6299; obj.Texts.Add(" Benefits"); return new COA { Code = 83, Project = project, Program = program, Function = function, Object = obj }; }
        public static COA _84() { var project = new COAItem(); project.Numbers.Add(1000); project.Texts.Add("GENERAL FUND"); project.Texts.Add("Schoolwide Project"); var program = new COAItem(); program.Numbers.Add(620); program.Texts.Add("Athletics"); var function = new COAItem(); function.Numbers = null; function.Texts = null; var obj = new COARange(); obj.InicialNumber = 6300; obj.FinalNumber = 6599; obj.Texts.Add(" Purchased Services"); return new COA { Code = 84, Project = project, Program = program, Function = function, Object = obj }; }
        public static COA _85() { var project = new COAItem(); project.Numbers.Add(1000); project.Texts.Add("GENERAL FUND"); project.Texts.Add("Schoolwide Project"); var program = new COAItem(); program.Numbers.Add(620); program.Texts.Add("Athletics"); var function = new COAItem(); function.Numbers = null; function.Texts = null; var obj = new COARange(); obj.InicialNumber = 6600; obj.FinalNumber = 6699; obj.Texts.Add(" Supplies"); return new COA { Code = 85, Project = project, Program = program, Function = function, Object = obj }; }
        public static COA _86() { var project = new COAItem(); project.Numbers.Add(1000); project.Texts.Add("GENERAL FUND"); project.Texts.Add("Schoolwide Project"); var program = new COAItem(); program.Numbers.Add(620); program.Texts.Add("Athletics"); var function = new COAItem(); function.Numbers = null; function.Texts = null; var obj = new COARange(); obj.InicialNumber = 6800; obj.FinalNumber = 6899; obj.Texts.Add(" Other"); return new COA { Code = 86, Project = project, Program = program, Function = function, Object = obj }; }
        public static COA _87() { var project = new COAItem(); project.Numbers.Add(1000); project.Texts.Add("GENERAL FUND"); project.Texts.Add("Schoolwide Project"); var program = new COAItem(); program.Numbers.Add(630); program.Numbers.Add(700); program.Numbers.Add(800); program.Numbers.Add(900); program.Texts = null; var function = new COAItem(); function.Numbers = null; function.Texts = null; var obj = new COARange(); obj.InicialNumber = 6100; obj.FinalNumber = 6199; obj.Texts.Add(" Salaries"); return new COA { Code = 87, Project = project, Program = program, Function = function, Object = obj }; }
        public static COA _88() { var project = new COAItem(); project.Numbers.Add(1000); project.Texts.Add("GENERAL FUND"); project.Texts.Add("Schoolwide Project"); var program = new COAItem(); program.Numbers.Add(630); program.Numbers.Add(700); program.Numbers.Add(800); program.Numbers.Add(900); program.Texts = null; var function = new COAItem(); function.Numbers = null; function.Texts = null; var obj = new COARange(); obj.InicialNumber = 6200; obj.FinalNumber = 6299; obj.Texts.Add(" Benefits"); return new COA { Code = 88, Project = project, Program = program, Function = function, Object = obj }; }
        public static COA _89() { var project = new COAItem(); project.Numbers.Add(1000); project.Texts.Add("GENERAL FUND"); project.Texts.Add("Schoolwide Project"); var program = new COAItem(); program.Numbers.Add(630); program.Numbers.Add(700); program.Numbers.Add(800); program.Numbers.Add(900); program.Texts = null; var function = new COAItem(); function.Numbers = null; function.Texts = null; var obj = new COARange(); obj.InicialNumber = 6300; obj.FinalNumber = 6599; obj.Texts.Add(" Purchased Services"); return new COA { Code = 89, Project = project, Program = program, Function = function, Object = obj }; }
        public static COA _90() { var project = new COAItem(); project.Numbers.Add(1000); project.Texts.Add("GENERAL FUND"); project.Texts.Add("Schoolwide Project"); var program = new COAItem(); program.Numbers.Add(630); program.Numbers.Add(700); program.Numbers.Add(800); program.Numbers.Add(900); program.Texts = null; var function = new COAItem(); function.Numbers = null; function.Texts = null; var obj = new COARange(); obj.InicialNumber = 6600; obj.FinalNumber = 6699; obj.Texts.Add(" Supplies"); return new COA { Code = 90, Project = project, Program = program, Function = function, Object = obj }; }
        public static COA _91() { var project = new COAItem(); project.Numbers.Add(1000); project.Texts.Add("GENERAL FUND"); project.Texts.Add("Schoolwide Project"); var program = new COAItem(); program.Numbers.Add(630); program.Numbers.Add(700); program.Numbers.Add(800); program.Numbers.Add(900); program.Texts = null; var function = new COAItem(); function.Numbers = null; function.Texts = null; var obj = new COARange(); obj.InicialNumber = 6800; obj.FinalNumber = 6899; obj.Texts.Add(" Other"); return new COA { Code = 91, Project = project, Program = program, Function = function, Object = obj }; }
        public static COA _92() { var project = new COAItem(); project.Numbers.Add(1000); project.Texts.Add("GENERAL FUND"); project.Texts.Add("Schoolwide Project"); var program = new COAItem(); program.Numbers.Add(200); program.Texts.Add("Special Education"); var function = new COAItem(); function.Numbers.Add(1000); function.Texts.Add("Instructional"); var obj = new COARange(); obj.InicialNumber = 6100; obj.FinalNumber = 6199; obj.Texts.Add(" Salaries"); return new COA { Code = 92, Project = project, Program = program, Function = function, Object = obj }; }
        public static COA _93() { var project = new COAItem(); project.Numbers.Add(1000); project.Texts.Add("GENERAL FUND"); project.Texts.Add("Schoolwide Project"); var program = new COAItem(); program.Numbers.Add(200); program.Texts.Add("Special Education"); var function = new COAItem(); function.Numbers.Add(1000); function.Texts.Add("Instructional"); var obj = new COARange(); obj.InicialNumber = 6200; obj.FinalNumber = 6299; obj.Texts.Add(" Benefits"); return new COA { Code = 93, Project = project, Program = program, Function = function, Object = obj }; }
        public static COA _94() { var project = new COAItem(); project.Numbers.Add(1000); project.Texts.Add("GENERAL FUND"); project.Texts.Add("Schoolwide Project"); var program = new COAItem(); program.Numbers.Add(200); program.Texts.Add("Special Education"); var function = new COAItem(); function.Numbers.Add(1000); function.Texts.Add("Instructional"); var obj = new COARange(); obj.InicialNumber = 6300; obj.FinalNumber = 6599; obj.Texts.Add(" Purchased Services"); return new COA { Code = 94, Project = project, Program = program, Function = function, Object = obj }; }
        public static COA _95() { var project = new COAItem(); project.Numbers.Add(1000); project.Texts.Add("GENERAL FUND"); project.Texts.Add("Schoolwide Project"); var program = new COAItem(); program.Numbers.Add(200); program.Texts.Add("Special Education"); var function = new COAItem(); function.Numbers.Add(1000); function.Texts.Add("Instructional"); var obj = new COARange(); obj.InicialNumber = 6600; obj.FinalNumber = 6699; obj.Texts.Add(" Supplies"); return new COA { Code = 95, Project = project, Program = program, Function = function, Object = obj }; }
        public static COA _96() { var project = new COAItem(); project.Numbers.Add(1000); project.Texts.Add("GENERAL FUND"); project.Texts.Add("Schoolwide Project"); var program = new COAItem(); program.Numbers.Add(200); program.Texts.Add("Special Education"); var function = new COAItem(); function.Numbers.Add(1000); function.Texts.Add("Instructional"); var obj = new COARange(); obj.InicialNumber = 6800; obj.FinalNumber = 6899; obj.Texts.Add(" Other"); return new COA { Code = 96, Project = project, Program = program, Function = function, Object = obj }; }
        public static COA _97() { var project = new COAItem(); project.Numbers.Add(1000); project.Texts.Add("GENERAL FUND"); project.Texts.Add("Schoolwide Project"); var program = new COAItem(); program.Numbers.Add(200); program.Texts.Add("Special Education"); var function = new COAItem(); function.Numbers.Add(2100); function.Texts.Add("Student Support"); var obj = new COARange(); obj.InicialNumber = 6100; obj.FinalNumber = 6199; obj.Texts.Add(" Salaries"); return new COA { Code = 97, Project = project, Program = program, Function = function, Object = obj }; }
        public static COA _98() { var project = new COAItem(); project.Numbers.Add(1000); project.Texts.Add("GENERAL FUND"); project.Texts.Add("Schoolwide Project"); var program = new COAItem(); program.Numbers.Add(200); program.Texts.Add("Special Education"); var function = new COAItem(); function.Numbers.Add(2100); function.Texts.Add("Student Support"); var obj = new COARange(); obj.InicialNumber = 6200; obj.FinalNumber = 6299; obj.Texts.Add(" Benefits"); return new COA { Code = 98, Project = project, Program = program, Function = function, Object = obj }; }
        public static COA _99() { var project = new COAItem(); project.Numbers.Add(1000); project.Texts.Add("GENERAL FUND"); project.Texts.Add("Schoolwide Project"); var program = new COAItem(); program.Numbers.Add(200); program.Texts.Add("Special Education"); var function = new COAItem(); function.Numbers.Add(2100); function.Texts.Add("Student Support"); var obj = new COARange(); obj.InicialNumber = 6300; obj.FinalNumber = 6599; obj.Texts.Add(" Purchased Services"); return new COA { Code = 99, Project = project, Program = program, Function = function, Object = obj }; }
        public static COA _100() { var project = new COAItem(); project.Numbers.Add(1000); project.Texts.Add("GENERAL FUND"); project.Texts.Add("Schoolwide Project"); var program = new COAItem(); program.Numbers.Add(200); program.Texts.Add("Special Education"); var function = new COAItem(); function.Numbers.Add(2100); function.Texts.Add("Student Support"); var obj = new COARange(); obj.InicialNumber = 6600; obj.FinalNumber = 6699; obj.Texts.Add(" Supplies"); return new COA { Code = 100, Project = project, Program = program, Function = function, Object = obj }; }
        public static COA _101() { var project = new COAItem(); project.Numbers.Add(1000); project.Texts.Add("GENERAL FUND"); project.Texts.Add("Schoolwide Project"); var program = new COAItem(); program.Numbers.Add(200); program.Texts.Add("Special Education"); var function = new COAItem(); function.Numbers.Add(2100); function.Texts.Add("Student Support"); var obj = new COARange(); obj.InicialNumber = 6800; obj.FinalNumber = 6899; obj.Texts.Add(" Other"); return new COA { Code = 101, Project = project, Program = program, Function = function, Object = obj }; }
        public static COA _102() { var project = new COAItem(); project.Numbers.Add(1000); project.Texts.Add("GENERAL FUND"); project.Texts.Add("Schoolwide Project"); var program = new COAItem(); program.Numbers.Add(200); program.Texts.Add("Special Education"); var function = new COAItem(); function.Numbers.Add(2200); function.Texts.Add("Teacher Support"); var obj = new COARange(); obj.InicialNumber = 6100; obj.FinalNumber = 6199; obj.Texts.Add(" Salaries"); return new COA { Code = 102, Project = project, Program = program, Function = function, Object = obj }; }
        public static COA _103() { var project = new COAItem(); project.Numbers.Add(1000); project.Texts.Add("GENERAL FUND"); project.Texts.Add("Schoolwide Project"); var program = new COAItem(); program.Numbers.Add(200); program.Texts.Add("Special Education"); var function = new COAItem(); function.Numbers.Add(2200); function.Texts.Add("Teacher Support"); var obj = new COARange(); obj.InicialNumber = 6200; obj.FinalNumber = 6299; obj.Texts.Add(" Benefits"); return new COA { Code = 103, Project = project, Program = program, Function = function, Object = obj }; }
        public static COA _104() { var project = new COAItem(); project.Numbers.Add(1000); project.Texts.Add("GENERAL FUND"); project.Texts.Add("Schoolwide Project"); var program = new COAItem(); program.Numbers.Add(200); program.Texts.Add("Special Education"); var function = new COAItem(); function.Numbers.Add(2200); function.Texts.Add("Teacher Support"); var obj = new COARange(); obj.InicialNumber = 6300; obj.FinalNumber = 6599; obj.Texts.Add(" Purchased Services"); return new COA { Code = 104, Project = project, Program = program, Function = function, Object = obj }; }
        public static COA _105() { var project = new COAItem(); project.Numbers.Add(1000); project.Texts.Add("GENERAL FUND"); project.Texts.Add("Schoolwide Project"); var program = new COAItem(); program.Numbers.Add(200); program.Texts.Add("Special Education"); var function = new COAItem(); function.Numbers.Add(2200); function.Texts.Add("Teacher Support"); var obj = new COARange(); obj.InicialNumber = 6600; obj.FinalNumber = 6699; obj.Texts.Add(" Supplies"); return new COA { Code = 105, Project = project, Program = program, Function = function, Object = obj }; }
        public static COA _106() { var project = new COAItem(); project.Numbers.Add(1000); project.Texts.Add("GENERAL FUND"); project.Texts.Add("Schoolwide Project"); var program = new COAItem(); program.Numbers.Add(200); program.Texts.Add("Special Education"); var function = new COAItem(); function.Numbers.Add(2200); function.Texts.Add("Teacher Support"); var obj = new COARange(); obj.InicialNumber = 6800; obj.FinalNumber = 6899; obj.Texts.Add(" Other"); return new COA { Code = 106, Project = project, Program = program, Function = function, Object = obj }; }
        public static COA _107() { var project = new COAItem(); project.Numbers.Add(1000); project.Texts.Add("GENERAL FUND"); project.Texts.Add("Schoolwide Project"); var program = new COAItem(); program.Numbers.Add(200); program.Texts.Add("Special Education"); var function = new COAItem(); function.Numbers.Add(2300); function.Texts.Add("General Administration"); var obj = new COARange(); obj.InicialNumber = 6100; obj.FinalNumber = 6199; obj.Texts.Add(" Salaries"); return new COA { Code = 107, Project = project, Program = program, Function = function, Object = obj }; }
        public static COA _108() { var project = new COAItem(); project.Numbers.Add(1000); project.Texts.Add("GENERAL FUND"); project.Texts.Add("Schoolwide Project"); var program = new COAItem(); program.Numbers.Add(200); program.Texts.Add("Special Education"); var function = new COAItem(); function.Numbers.Add(2300); function.Texts.Add("General Administration"); var obj = new COARange(); obj.InicialNumber = 6200; obj.FinalNumber = 6299; obj.Texts.Add(" Benefits"); return new COA { Code = 108, Project = project, Program = program, Function = function, Object = obj }; }
        public static COA _109() { var project = new COAItem(); project.Numbers.Add(1000); project.Texts.Add("GENERAL FUND"); project.Texts.Add("Schoolwide Project"); var program = new COAItem(); program.Numbers.Add(200); program.Texts.Add("Special Education"); var function = new COAItem(); function.Numbers.Add(2300); function.Texts.Add("General Administration"); var obj = new COARange(); obj.InicialNumber = 6300; obj.FinalNumber = 6599; obj.Texts.Add(" Purchased Services"); return new COA { Code = 109, Project = project, Program = program, Function = function, Object = obj }; }
        public static COA _110() { var project = new COAItem(); project.Numbers.Add(1000); project.Texts.Add("GENERAL FUND"); project.Texts.Add("Schoolwide Project"); var program = new COAItem(); program.Numbers.Add(200); program.Texts.Add("Special Education"); var function = new COAItem(); function.Numbers.Add(2300); function.Texts.Add("General Administration"); var obj = new COARange(); obj.InicialNumber = 6600; obj.FinalNumber = 6699; obj.Texts.Add(" Supplies"); return new COA { Code = 110, Project = project, Program = program, Function = function, Object = obj }; }
        public static COA _111() { var project = new COAItem(); project.Numbers.Add(1000); project.Texts.Add("GENERAL FUND"); project.Texts.Add("Schoolwide Project"); var program = new COAItem(); program.Numbers.Add(200); program.Texts.Add("Special Education"); var function = new COAItem(); function.Numbers.Add(2300); function.Texts.Add("General Administration"); var obj = new COARange(); obj.InicialNumber = 6800; obj.FinalNumber = 6899; obj.Texts.Add(" Other"); return new COA { Code = 111, Project = project, Program = program, Function = function, Object = obj }; }
        public static COA _112() { var project = new COAItem(); project.Numbers.Add(1000); project.Texts.Add("GENERAL FUND"); project.Texts.Add("Schoolwide Project"); var program = new COAItem(); program.Numbers.Add(200); program.Texts.Add("Special Education"); var function = new COAItem(); function.Numbers.Add(2400); function.Texts.Add("School Administration"); var obj = new COARange(); obj.InicialNumber = 6100; obj.FinalNumber = 6199; obj.Texts.Add(" Salaries"); return new COA { Code = 112, Project = project, Program = program, Function = function, Object = obj }; }
        public static COA _113() { var project = new COAItem(); project.Numbers.Add(1000); project.Texts.Add("GENERAL FUND"); project.Texts.Add("Schoolwide Project"); var program = new COAItem(); program.Numbers.Add(200); program.Texts.Add("Special Education"); var function = new COAItem(); function.Numbers.Add(2400); function.Texts.Add("School Administration"); var obj = new COARange(); obj.InicialNumber = 6200; obj.FinalNumber = 6299; obj.Texts.Add(" Benefits"); return new COA { Code = 113, Project = project, Program = program, Function = function, Object = obj }; }
        public static COA _114() { var project = new COAItem(); project.Numbers.Add(1000); project.Texts.Add("GENERAL FUND"); project.Texts.Add("Schoolwide Project"); var program = new COAItem(); program.Numbers.Add(200); program.Texts.Add("Special Education"); var function = new COAItem(); function.Numbers.Add(2400); function.Texts.Add("School Administration"); var obj = new COARange(); obj.InicialNumber = 6300; obj.FinalNumber = 6599; obj.Texts.Add(" Purchased Services"); return new COA { Code = 114, Project = project, Program = program, Function = function, Object = obj }; }
        public static COA _115() { var project = new COAItem(); project.Numbers.Add(1000); project.Texts.Add("GENERAL FUND"); project.Texts.Add("Schoolwide Project"); var program = new COAItem(); program.Numbers.Add(200); program.Texts.Add("Special Education"); var function = new COAItem(); function.Numbers.Add(2400); function.Texts.Add("School Administration"); var obj = new COARange(); obj.InicialNumber = 6600; obj.FinalNumber = 6699; obj.Texts.Add(" Supplies"); return new COA { Code = 115, Project = project, Program = program, Function = function, Object = obj }; }
        public static COA _116() { var project = new COAItem(); project.Numbers.Add(1000); project.Texts.Add("GENERAL FUND"); project.Texts.Add("Schoolwide Project"); var program = new COAItem(); program.Numbers.Add(200); program.Texts.Add("Special Education"); var function = new COAItem(); function.Numbers.Add(2400); function.Texts.Add("School Administration"); var obj = new COARange(); obj.InicialNumber = 6800; obj.FinalNumber = 6899; obj.Texts.Add(" Other"); return new COA { Code = 116, Project = project, Program = program, Function = function, Object = obj }; }
        public static COA _117() { var project = new COAItem(); project.Numbers.Add(1000); project.Texts.Add("GENERAL FUND"); project.Texts.Add("Schoolwide Project"); var program = new COAItem(); program.Numbers.Add(200); program.Texts.Add("Special Education"); var function = new COAItem(); function.Numbers.Add(2500); function.Texts.Add("Central Services"); var obj = new COARange(); obj.InicialNumber = 6100; obj.FinalNumber = 6199; obj.Texts.Add(" Salaries"); return new COA { Code = 117, Project = project, Program = program, Function = function, Object = obj }; }
        public static COA _118() { var project = new COAItem(); project.Numbers.Add(1000); project.Texts.Add("GENERAL FUND"); project.Texts.Add("Schoolwide Project"); var program = new COAItem(); program.Numbers.Add(200); program.Texts.Add("Special Education"); var function = new COAItem(); function.Numbers.Add(2500); function.Texts.Add("Central Services"); var obj = new COARange(); obj.InicialNumber = 6200; obj.FinalNumber = 6299; obj.Texts.Add(" Benefits"); return new COA { Code = 118, Project = project, Program = program, Function = function, Object = obj }; }
        public static COA _119() { var project = new COAItem(); project.Numbers.Add(1000); project.Texts.Add("GENERAL FUND"); project.Texts.Add("Schoolwide Project"); var program = new COAItem(); program.Numbers.Add(200); program.Texts.Add("Special Education"); var function = new COAItem(); function.Numbers.Add(2500); function.Texts.Add("Central Services"); var obj = new COARange(); obj.InicialNumber = 6300; obj.FinalNumber = 6599; obj.Texts.Add(" Purchased Services"); return new COA { Code = 119, Project = project, Program = program, Function = function, Object = obj }; }
        public static COA _120() { var project = new COAItem(); project.Numbers.Add(1000); project.Texts.Add("GENERAL FUND"); project.Texts.Add("Schoolwide Project"); var program = new COAItem(); program.Numbers.Add(200); program.Texts.Add("Special Education"); var function = new COAItem(); function.Numbers.Add(2500); function.Texts.Add("Central Services"); var obj = new COARange(); obj.InicialNumber = 6600; obj.FinalNumber = 6699; obj.Texts.Add(" Supplies"); return new COA { Code = 120, Project = project, Program = program, Function = function, Object = obj }; }
        public static COA _121() { var project = new COAItem(); project.Numbers.Add(1000); project.Texts.Add("GENERAL FUND"); project.Texts.Add("Schoolwide Project"); var program = new COAItem(); program.Numbers.Add(200); program.Texts.Add("Special Education"); var function = new COAItem(); function.Numbers.Add(2500); function.Texts.Add("Central Services"); var obj = new COARange(); obj.InicialNumber = 6800; obj.FinalNumber = 6899; obj.Texts.Add(" Other"); return new COA { Code = 121, Project = project, Program = program, Function = function, Object = obj }; }
        public static COA _122() { var project = new COAItem(); project.Numbers.Add(1000); project.Texts.Add("GENERAL FUND"); project.Texts.Add("Schoolwide Project"); var program = new COAItem(); program.Numbers.Add(200); program.Texts.Add("Special Education"); var function = new COAItem(); function.Numbers.Add(2600); function.Texts.Add(" Plant or Facility"); var obj = new COARange(); obj.InicialNumber = 6100; obj.FinalNumber = 6199; obj.Texts.Add(" Salaries"); return new COA { Code = 122, Project = project, Program = program, Function = function, Object = obj }; }
        public static COA _123() { var project = new COAItem(); project.Numbers.Add(1000); project.Texts.Add("GENERAL FUND"); project.Texts.Add("Schoolwide Project"); var program = new COAItem(); program.Numbers.Add(200); program.Texts.Add("Special Education"); var function = new COAItem(); function.Numbers.Add(2600); function.Texts.Add(" Plant or Facility"); var obj = new COARange(); obj.InicialNumber = 6200; obj.FinalNumber = 6299; obj.Texts.Add(" Benefits"); return new COA { Code = 123, Project = project, Program = program, Function = function, Object = obj }; }
        public static COA _124() { var project = new COAItem(); project.Numbers.Add(1000); project.Texts.Add("GENERAL FUND"); project.Texts.Add("Schoolwide Project"); var program = new COAItem(); program.Numbers.Add(200); program.Texts.Add("Special Education"); var function = new COAItem(); function.Numbers.Add(2600); function.Texts.Add(" Plant or Facility"); var obj = new COARange(); obj.InicialNumber = 6300; obj.FinalNumber = 6599; obj.Texts.Add(" Purchased Services"); return new COA { Code = 124, Project = project, Program = program, Function = function, Object = obj }; }
        public static COA _125() { var project = new COAItem(); project.Numbers.Add(1000); project.Texts.Add("GENERAL FUND"); project.Texts.Add("Schoolwide Project"); var program = new COAItem(); program.Numbers.Add(200); program.Texts.Add("Special Education"); var function = new COAItem(); function.Numbers.Add(2600); function.Texts.Add(" Plant or Facility"); var obj = new COARange(); obj.InicialNumber = 6600; obj.FinalNumber = 6699; obj.Texts.Add(" Supplies"); return new COA { Code = 125, Project = project, Program = program, Function = function, Object = obj }; }
        public static COA _126() { var project = new COAItem(); project.Numbers.Add(1000); project.Texts.Add("GENERAL FUND"); project.Texts.Add("Schoolwide Project"); var program = new COAItem(); program.Numbers.Add(200); program.Texts.Add("Special Education"); var function = new COAItem(); function.Numbers.Add(2600); function.Texts.Add(" Plant or Facility"); var obj = new COARange(); obj.InicialNumber = 6800; obj.FinalNumber = 6899; obj.Texts.Add(" Other"); return new COA { Code = 126, Project = project, Program = program, Function = function, Object = obj }; }
        public static COA _127() { var project = new COAItem(); project.Numbers.Add(1000); project.Texts.Add("GENERAL FUND"); project.Texts.Add("Schoolwide Project"); var program = new COAItem(); program.Numbers.Add(200); program.Texts.Add("Special Education"); var function = new COAItem(); function.Numbers.Add(2900); function.Texts.Add("Other"); var obj = new COARange(); obj.InicialNumber = 6100; obj.FinalNumber = 6199; obj.Texts.Add(" Salaries"); return new COA { Code = 127, Project = project, Program = program, Function = function, Object = obj }; }
        public static COA _128() { var project = new COAItem(); project.Numbers.Add(1000); project.Texts.Add("GENERAL FUND"); project.Texts.Add("Schoolwide Project"); var program = new COAItem(); program.Numbers.Add(200); program.Texts.Add("Special Education"); var function = new COAItem(); function.Numbers.Add(2900); function.Texts.Add("Other"); var obj = new COARange(); obj.InicialNumber = 6200; obj.FinalNumber = 6299; obj.Texts.Add(" Benefits"); return new COA { Code = 128, Project = project, Program = program, Function = function, Object = obj }; }
        public static COA _129() { var project = new COAItem(); project.Numbers.Add(1000); project.Texts.Add("GENERAL FUND"); project.Texts.Add("Schoolwide Project"); var program = new COAItem(); program.Numbers.Add(200); program.Texts.Add("Special Education"); var function = new COAItem(); function.Numbers.Add(2900); function.Texts.Add("Other"); var obj = new COARange(); obj.InicialNumber = 6300; obj.FinalNumber = 6599; obj.Texts.Add(" Purchased Services"); return new COA { Code = 129, Project = project, Program = program, Function = function, Object = obj }; }
        public static COA _130() { var project = new COAItem(); project.Numbers.Add(1000); project.Texts.Add("GENERAL FUND"); project.Texts.Add("Schoolwide Project"); var program = new COAItem(); program.Numbers.Add(200); program.Texts.Add("Special Education"); var function = new COAItem(); function.Numbers.Add(2900); function.Texts.Add("Other"); var obj = new COARange(); obj.InicialNumber = 6600; obj.FinalNumber = 6699; obj.Texts.Add(" Supplies"); return new COA { Code = 130, Project = project, Program = program, Function = function, Object = obj }; }
        public static COA _131() { var project = new COAItem(); project.Numbers.Add(1000); project.Texts.Add("GENERAL FUND"); project.Texts.Add("Schoolwide Project"); var program = new COAItem(); program.Numbers.Add(200); program.Texts.Add("Special Education"); var function = new COAItem(); function.Numbers.Add(2900); function.Texts.Add("Other"); var obj = new COARange(); obj.InicialNumber = 6800; obj.FinalNumber = 6899; obj.Texts.Add(" Other"); return new COA { Code = 131, Project = project, Program = program, Function = function, Object = obj }; }
        public static COA _132() { var project = new COAItem(); project.Numbers.Add(1000); project.Texts.Add("GENERAL FUND"); project.Texts.Add("Schoolwide Project"); var program = new COAItem(); program.Numbers.Add(200); program.Texts.Add("Special Education"); var function = new COAItem(); function.Numbers.Add(3000); function.Texts.Add("9 or Noninstructional "); var obj = new COARange(); obj.InicialNumber = 6100; obj.FinalNumber = 6199; obj.Texts.Add(" Salaries"); return new COA { Code = 132, Project = project, Program = program, Function = function, Object = obj }; }
        public static COA _133() { var project = new COAItem(); project.Numbers.Add(1000); project.Texts.Add("GENERAL FUND"); project.Texts.Add("Schoolwide Project"); var program = new COAItem(); program.Numbers.Add(200); program.Texts.Add("Special Education"); var function = new COAItem(); function.Numbers.Add(3000); function.Texts.Add("9 or Noninstructional "); var obj = new COARange(); obj.InicialNumber = 6200; obj.FinalNumber = 6299; obj.Texts.Add(" Benefits"); return new COA { Code = 133, Project = project, Program = program, Function = function, Object = obj }; }
        public static COA _134() { var project = new COAItem(); project.Numbers.Add(1000); project.Texts.Add("GENERAL FUND"); project.Texts.Add("Schoolwide Project"); var program = new COAItem(); program.Numbers.Add(200); program.Texts.Add("Special Education"); var function = new COAItem(); function.Numbers.Add(3000); function.Texts.Add("9 or Noninstructional "); var obj = new COARange(); obj.InicialNumber = 6300; obj.FinalNumber = 6599; obj.Texts.Add(" Purchased Services"); return new COA { Code = 134, Project = project, Program = program, Function = function, Object = obj }; }
        public static COA _135() { var project = new COAItem(); project.Numbers.Add(1000); project.Texts.Add("GENERAL FUND"); project.Texts.Add("Schoolwide Project"); var program = new COAItem(); program.Numbers.Add(200); program.Texts.Add("Special Education"); var function = new COAItem(); function.Numbers.Add(3000); function.Texts.Add("9 or Noninstructional "); var obj = new COARange(); obj.InicialNumber = 6600; obj.FinalNumber = 6699; obj.Texts.Add(" Supplies"); return new COA { Code = 135, Project = project, Program = program, Function = function, Object = obj }; }
        public static COA _136() { var project = new COAItem(); project.Numbers.Add(1000); project.Texts.Add("GENERAL FUND"); project.Texts.Add("Schoolwide Project"); var program = new COAItem(); program.Numbers.Add(200); program.Texts.Add("Special Education"); var function = new COAItem(); function.Numbers.Add(3000); function.Texts.Add("9 or Noninstructional "); var obj = new COARange(); obj.InicialNumber = 6800; obj.FinalNumber = 6899; obj.Texts.Add(" Other"); return new COA { Code = 136, Project = project, Program = program, Function = function, Object = obj }; }
        public static COA _137() { var project = new COAItem(); project.Numbers.Add(1000); project.Texts.Add("GENERAL FUND"); project.Texts.Add("Schoolwide Project"); var program = new COAItem(); program.Numbers.Add(200); program.Texts.Add("Special Education"); var function = new COAItem(); function.Numbers.Add(4000); function.Texts.Add("Facility Acquisition"); var obj = new COARange(); obj.InicialNumber = 6100; obj.FinalNumber = 6199; obj.Texts.Add(" Salaries"); return new COA { Code = 137, Project = project, Program = program, Function = function, Object = obj }; }
        public static COA _138() { var project = new COAItem(); project.Numbers.Add(1000); project.Texts.Add("GENERAL FUND"); project.Texts.Add("Schoolwide Project"); var program = new COAItem(); program.Numbers.Add(200); program.Texts.Add("Special Education"); var function = new COAItem(); function.Numbers.Add(4000); function.Texts.Add("Facility Acquisition"); var obj = new COARange(); obj.InicialNumber = 6200; obj.FinalNumber = 6299; obj.Texts.Add(" Benefits"); return new COA { Code = 138, Project = project, Program = program, Function = function, Object = obj }; }
        public static COA _139() { var project = new COAItem(); project.Numbers.Add(1000); project.Texts.Add("GENERAL FUND"); project.Texts.Add("Schoolwide Project"); var program = new COAItem(); program.Numbers.Add(200); program.Texts.Add("Special Education"); var function = new COAItem(); function.Numbers.Add(4000); function.Texts.Add("Facility Acquisition"); var obj = new COARange(); obj.InicialNumber = 6300; obj.FinalNumber = 6599; obj.Texts.Add(" Purchased Services"); return new COA { Code = 139, Project = project, Program = program, Function = function, Object = obj }; }
        public static COA _140() { var project = new COAItem(); project.Numbers.Add(1000); project.Texts.Add("GENERAL FUND"); project.Texts.Add("Schoolwide Project"); var program = new COAItem(); program.Numbers.Add(200); program.Texts.Add("Special Education"); var function = new COAItem(); function.Numbers.Add(4000); function.Texts.Add("Facility Acquisition"); var obj = new COARange(); obj.InicialNumber = 6600; obj.FinalNumber = 6699; obj.Texts.Add(" Supplies"); return new COA { Code = 140, Project = project, Program = program, Function = function, Object = obj }; }
        public static COA _141() { var project = new COAItem(); project.Numbers.Add(1000); project.Texts.Add("GENERAL FUND"); project.Texts.Add("Schoolwide Project"); var program = new COAItem(); program.Numbers.Add(200); program.Texts.Add("Special Education"); var function = new COAItem(); function.Numbers.Add(4000); function.Texts.Add("Facility Acquisition"); var obj = new COARange(); obj.InicialNumber = 6800; obj.FinalNumber = 6899; obj.Texts.Add(" Other"); return new COA { Code = 141, Project = project, Program = program, Function = function, Object = obj }; }
        public static COA _142() { var project = new COAItem(); project.Numbers.Add(1000); project.Texts.Add("GENERAL FUND"); project.Texts.Add("Schoolwide Project"); var program = new COAItem(); program.Numbers.Add(200); program.Texts.Add("Special Education"); var function = new COAItem(); function.Numbers.Add(5000); function.Texts.Add("Debt Service"); var obj = new COARange(); obj.InicialNumber = 6100; obj.FinalNumber = 6199; obj.Texts.Add(" Salaries"); return new COA { Code = 142, Project = project, Program = program, Function = function, Object = obj }; }
        public static COA _143() { var project = new COAItem(); project.Numbers.Add(1000); project.Texts.Add("GENERAL FUND"); project.Texts.Add("Schoolwide Project"); var program = new COAItem(); program.Numbers.Add(200); program.Texts.Add("Special Education"); var function = new COAItem(); function.Numbers.Add(5000); function.Texts.Add("Debt Service"); var obj = new COARange(); obj.InicialNumber = 6200; obj.FinalNumber = 6299; obj.Texts.Add(" Benefits"); return new COA { Code = 143, Project = project, Program = program, Function = function, Object = obj }; }
        public static COA _144() { var project = new COAItem(); project.Numbers.Add(1000); project.Texts.Add("GENERAL FUND"); project.Texts.Add("Schoolwide Project"); var program = new COAItem(); program.Numbers.Add(200); program.Texts.Add("Special Education"); var function = new COAItem(); function.Numbers.Add(5000); function.Texts.Add("Debt Service"); var obj = new COARange(); obj.InicialNumber = 6300; obj.FinalNumber = 6599; obj.Texts.Add(" Purchased Services"); return new COA { Code = 144, Project = project, Program = program, Function = function, Object = obj }; }
        public static COA _145() { var project = new COAItem(); project.Numbers.Add(1000); project.Texts.Add("GENERAL FUND"); project.Texts.Add("Schoolwide Project"); var program = new COAItem(); program.Numbers.Add(200); program.Texts.Add("Special Education"); var function = new COAItem(); function.Numbers.Add(5000); function.Texts.Add("Debt Service"); var obj = new COARange(); obj.InicialNumber = 6600; obj.FinalNumber = 6699; obj.Texts.Add(" Supplies"); return new COA { Code = 145, Project = project, Program = program, Function = function, Object = obj }; }
        public static COA _146() { var project = new COAItem(); project.Numbers.Add(1000); project.Texts.Add("GENERAL FUND"); project.Texts.Add("Schoolwide Project"); var program = new COAItem(); program.Numbers.Add(200); program.Texts.Add("Special Education"); var function = new COAItem(); function.Numbers.Add(5000); function.Texts.Add("Debt Service"); var obj = new COARange(); obj.InicialNumber = 6800; obj.FinalNumber = 6899; obj.Texts.Add(" Other"); return new COA { Code = 146, Project = project, Program = program, Function = function, Object = obj }; }
        public static COA _147() { var project = new COAItem(); project.Numbers.Add(1000); project.Texts.Add("GENERAL FUND"); project.Texts.Add("Schoolwide Project"); var program = new COAItem(); program.Numbers.Add(300); program.Texts = null; var function = new COAItem(); function.Numbers = null; function.Texts = null; var obj = new COARange(); obj.InicialNumber = 6100; obj.FinalNumber = 6199; obj.Texts.Add(" Salaries"); return new COA { Code = 147, Project = project, Program = program, Function = function, Object = obj }; }
        public static COA _148() { var project = new COAItem(); project.Numbers.Add(1000); project.Texts.Add("GENERAL FUND"); project.Texts.Add("Schoolwide Project"); var program = new COAItem(); program.Numbers.Add(300); program.Texts = null; var function = new COAItem(); function.Numbers = null; function.Texts = null; var obj = new COARange(); obj.InicialNumber = 6200; obj.FinalNumber = 6299; obj.Texts.Add(" Benefits"); return new COA { Code = 148, Project = project, Program = program, Function = function, Object = obj }; }
        public static COA _149() { var project = new COAItem(); project.Numbers.Add(1000); project.Texts.Add("GENERAL FUND"); project.Texts.Add("Schoolwide Project"); var program = new COAItem(); program.Numbers.Add(300); program.Texts = null; var function = new COAItem(); function.Numbers = null; function.Texts = null; var obj = new COARange(); obj.InicialNumber = 6300; obj.FinalNumber = 6599; obj.Texts.Add(" Purchased Services"); return new COA { Code = 149, Project = project, Program = program, Function = function, Object = obj }; }
        public static COA _150() { var project = new COAItem(); project.Numbers.Add(1000); project.Texts.Add("GENERAL FUND"); project.Texts.Add("Schoolwide Project"); var program = new COAItem(); program.Numbers.Add(300); program.Texts = null; var function = new COAItem(); function.Numbers = null; function.Texts = null; var obj = new COARange(); obj.InicialNumber = 6600; obj.FinalNumber = 6699; obj.Texts.Add(" Supplies"); return new COA { Code = 150, Project = project, Program = program, Function = function, Object = obj }; }
        public static COA _151() { var project = new COAItem(); project.Numbers.Add(1000); project.Texts.Add("GENERAL FUND"); project.Texts.Add("Schoolwide Project"); var program = new COAItem(); program.Numbers.Add(300); program.Texts = null; var function = new COAItem(); function.Numbers = null; function.Texts = null; var obj = new COARange(); obj.InicialNumber = 6800; obj.FinalNumber = 6899; obj.Texts.Add(" Other"); return new COA { Code = 151, Project = project, Program = program, Function = function, Object = obj }; }
        public static COA _152() { var project = new COAItem(); project.Numbers.Add(1000); project.Texts.Add("GENERAL FUND"); project.Texts.Add("Schoolwide Project"); var program = new COAItem(); program.Numbers.Add(400); program.Texts = null; var function = new COAItem(); function.Numbers = null; function.Texts = null; var obj = new COARange(); obj.InicialNumber = 6100; obj.FinalNumber = 6199; obj.Texts.Add(" Salaries"); return new COA { Code = 152, Project = project, Program = program, Function = function, Object = obj }; }
        public static COA _153() { var project = new COAItem(); project.Numbers.Add(1000); project.Texts.Add("GENERAL FUND"); project.Texts.Add("Schoolwide Project"); var program = new COAItem(); program.Numbers.Add(400); program.Texts = null; var function = new COAItem(); function.Numbers = null; function.Texts = null; var obj = new COARange(); obj.InicialNumber = 6200; obj.FinalNumber = 6299; obj.Texts.Add(" Benefits"); return new COA { Code = 153, Project = project, Program = program, Function = function, Object = obj }; }
        public static COA _154() { var project = new COAItem(); project.Numbers.Add(1000); project.Texts.Add("GENERAL FUND"); project.Texts.Add("Schoolwide Project"); var program = new COAItem(); program.Numbers.Add(400); program.Texts = null; var function = new COAItem(); function.Numbers = null; function.Texts = null; var obj = new COARange(); obj.InicialNumber = 6300; obj.FinalNumber = 6599; obj.Texts.Add(" Purchased Services"); return new COA { Code = 154, Project = project, Program = program, Function = function, Object = obj }; }
        public static COA _155() { var project = new COAItem(); project.Numbers.Add(1000); project.Texts.Add("GENERAL FUND"); project.Texts.Add("Schoolwide Project"); var program = new COAItem(); program.Numbers.Add(400); program.Texts = null; var function = new COAItem(); function.Numbers = null; function.Texts = null; var obj = new COARange(); obj.InicialNumber = 6600; obj.FinalNumber = 6699; obj.Texts.Add(" Supplies"); return new COA { Code = 155, Project = project, Program = program, Function = function, Object = obj }; }
        public static COA _156() { var project = new COAItem(); project.Numbers.Add(1000); project.Texts.Add("GENERAL FUND"); project.Texts.Add("Schoolwide Project"); var program = new COAItem(); program.Numbers.Add(400); program.Texts = null; var function = new COAItem(); function.Numbers = null; function.Texts = null; var obj = new COARange(); obj.InicialNumber = 6800; obj.FinalNumber = 6899; obj.Texts.Add(" Other"); return new COA { Code = 156, Project = project, Program = program, Function = function, Object = obj }; }
        public static COA _157() { var project = new COAItem(); project.Numbers.Add(1000); project.Texts.Add("GENERAL FUND"); project.Texts.Add("Schoolwide Project"); var program = new COAItem(); program.Numbers.Add(530); program.Texts = null; var function = new COAItem(); function.Numbers = null; function.Texts = null; var obj = new COARange(); obj.InicialNumber = 6100; obj.FinalNumber = 6199; obj.Texts.Add(" Salaries"); return new COA { Code = 157, Project = project, Program = program, Function = function, Object = obj }; }
        public static COA _158() { var project = new COAItem(); project.Numbers.Add(1000); project.Texts.Add("GENERAL FUND"); project.Texts.Add("Schoolwide Project"); var program = new COAItem(); program.Numbers.Add(530); program.Texts = null; var function = new COAItem(); function.Numbers = null; function.Texts = null; var obj = new COARange(); obj.InicialNumber = 6200; obj.FinalNumber = 6299; obj.Texts.Add(" Benefits"); return new COA { Code = 158, Project = project, Program = program, Function = function, Object = obj }; }
        public static COA _159() { var project = new COAItem(); project.Numbers.Add(1000); project.Texts.Add("GENERAL FUND"); project.Texts.Add("Schoolwide Project"); var program = new COAItem(); program.Numbers.Add(530); program.Texts = null; var function = new COAItem(); function.Numbers = null; function.Texts = null; var obj = new COARange(); obj.InicialNumber = 6300; obj.FinalNumber = 6599; obj.Texts.Add(" Purchased Services"); return new COA { Code = 159, Project = project, Program = program, Function = function, Object = obj }; }
        public static COA _160() { var project = new COAItem(); project.Numbers.Add(1000); project.Texts.Add("GENERAL FUND"); project.Texts.Add("Schoolwide Project"); var program = new COAItem(); program.Numbers.Add(530); program.Texts = null; var function = new COAItem(); function.Numbers = null; function.Texts = null; var obj = new COARange(); obj.InicialNumber = 6600; obj.FinalNumber = 6699; obj.Texts.Add(" Supplies"); return new COA { Code = 160, Project = project, Program = program, Function = function, Object = obj }; }
        public static COA _161() { var project = new COAItem(); project.Numbers.Add(1000); project.Texts.Add("GENERAL FUND"); project.Texts.Add("Schoolwide Project"); var program = new COAItem(); program.Numbers.Add(530); program.Texts = null; var function = new COAItem(); function.Numbers = null; function.Texts = null; var obj = new COARange(); obj.InicialNumber = 6800; obj.FinalNumber = 6899; obj.Texts.Add(" Other"); return new COA { Code = 161, Project = project, Program = program, Function = function, Object = obj }; }
        public static COA _162() { var project = new COAItem(); project.Numbers.Add(1000); project.Texts.Add("GENERAL FUND"); project.Texts.Add("Schoolwide Project"); var program = new COAItem(); program.Numbers.Add(540); program.Texts = null; var function = new COAItem(); function.Numbers = null; function.Texts = null; var obj = new COARange(); obj.InicialNumber = 6100; obj.FinalNumber = 6199; obj.Texts.Add(" Salaries"); return new COA { Code = 162, Project = project, Program = program, Function = function, Object = obj }; }
        public static COA _163() { var project = new COAItem(); project.Numbers.Add(1000); project.Texts.Add("GENERAL FUND"); project.Texts.Add("Schoolwide Project"); var program = new COAItem(); program.Numbers.Add(540); program.Texts = null; var function = new COAItem(); function.Numbers = null; function.Texts = null; var obj = new COARange(); obj.InicialNumber = 6200; obj.FinalNumber = 6299; obj.Texts.Add(" Benefits"); return new COA { Code = 163, Project = project, Program = program, Function = function, Object = obj }; }
        public static COA _164() { var project = new COAItem(); project.Numbers.Add(1000); project.Texts.Add("GENERAL FUND"); project.Texts.Add("Schoolwide Project"); var program = new COAItem(); program.Numbers.Add(540); program.Texts = null; var function = new COAItem(); function.Numbers = null; function.Texts = null; var obj = new COARange(); obj.InicialNumber = 6300; obj.FinalNumber = 6599; obj.Texts.Add(" Purchased Services"); return new COA { Code = 164, Project = project, Program = program, Function = function, Object = obj }; }
        public static COA _165() { var project = new COAItem(); project.Numbers.Add(1000); project.Texts.Add("GENERAL FUND"); project.Texts.Add("Schoolwide Project"); var program = new COAItem(); program.Numbers.Add(540); program.Texts = null; var function = new COAItem(); function.Numbers = null; function.Texts = null; var obj = new COARange(); obj.InicialNumber = 6600; obj.FinalNumber = 6699; obj.Texts.Add(" Supplies"); return new COA { Code = 165, Project = project, Program = program, Function = function, Object = obj }; }
        public static COA _166() { var project = new COAItem(); project.Numbers.Add(1000); project.Texts.Add("GENERAL FUND"); project.Texts.Add("Schoolwide Project"); var program = new COAItem(); program.Numbers.Add(540); program.Texts = null; var function = new COAItem(); function.Numbers = null; function.Texts = null; var obj = new COARange(); obj.InicialNumber = 6800; obj.FinalNumber = 6899; obj.Texts.Add(" Other"); return new COA { Code = 166, Project = project, Program = program, Function = function, Object = obj }; }
        public static COA _167() { var project = new COAItem(); project.Numbers.Add(1000); project.Texts.Add("GENERAL FUND"); project.Texts.Add("Schoolwide Project"); var program = new COAItem(); program.Numbers.Add(550); program.Texts = null; var function = new COAItem(); function.Numbers = null; function.Texts = null; var obj = new COARange(); obj.InicialNumber = 6100; obj.FinalNumber = 6199; obj.Texts.Add(" Salaries"); return new COA { Code = 167, Project = project, Program = program, Function = function, Object = obj }; }
        public static COA _168() { var project = new COAItem(); project.Numbers.Add(1000); project.Texts.Add("GENERAL FUND"); project.Texts.Add("Schoolwide Project"); var program = new COAItem(); program.Numbers.Add(550); program.Texts = null; var function = new COAItem(); function.Numbers = null; function.Texts = null; var obj = new COARange(); obj.InicialNumber = 6200; obj.FinalNumber = 6299; obj.Texts.Add(" Benefits"); return new COA { Code = 168, Project = project, Program = program, Function = function, Object = obj }; }
        public static COA _169() { var project = new COAItem(); project.Numbers.Add(1000); project.Texts.Add("GENERAL FUND"); project.Texts.Add("Schoolwide Project"); var program = new COAItem(); program.Numbers.Add(550); program.Texts = null; var function = new COAItem(); function.Numbers = null; function.Texts = null; var obj = new COARange(); obj.InicialNumber = 6300; obj.FinalNumber = 6599; obj.Texts.Add(" Purchased Services"); return new COA { Code = 169, Project = project, Program = program, Function = function, Object = obj }; }
        public static COA _170() { var project = new COAItem(); project.Numbers.Add(1000); project.Texts.Add("GENERAL FUND"); project.Texts.Add("Schoolwide Project"); var program = new COAItem(); program.Numbers.Add(550); program.Texts = null; var function = new COAItem(); function.Numbers = null; function.Texts = null; var obj = new COARange(); obj.InicialNumber = 6600; obj.FinalNumber = 6699; obj.Texts.Add(" Supplies"); return new COA { Code = 170, Project = project, Program = program, Function = function, Object = obj }; }
        public static COA _171() { var project = new COAItem(); project.Numbers.Add(1000); project.Texts.Add("GENERAL FUND"); project.Texts.Add("Schoolwide Project"); var program = new COAItem(); program.Numbers.Add(550); program.Texts = null; var function = new COAItem(); function.Numbers = null; function.Texts = null; var obj = new COARange(); obj.InicialNumber = 6800; obj.FinalNumber = 6899; obj.Texts.Add(" Other"); return new COA { Code = 171, Project = project, Program = program, Function = function, Object = obj }; }
        #endregion
    }
}
