USE [Quality_Control]
GO

/****** Object:  Table [dbo].[PROCESSAMENTO]    Script Date: 08/26/2013 13:53:19 ******/
IF  EXISTS (SELECT * FROM sys.objects WHERE object_id = OBJECT_ID(N'[dbo].[PROCESSAMENTO]') AND type in (N'U'))
DROP TABLE [dbo].[PROCESSAMENTO]
GO

USE [Quality_Control]
GO

/****** Object:  Table [dbo].[PROCESSAMENTO]    Script Date: 08/26/2013 13:53:19 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

SET ANSI_PADDING ON
GO

CREATE TABLE [dbo].[PROCESSAMENTO](
	[CD_PROCESSAMENTO] [int] NOT NULL,
	[DT_REFERENCIA] [smalldatetime] NOT NULL,
	[IN_PERIODO_PROCESSAMENTO] [char](1) NOT NULL,
	[IN_TIPO_PROCESSAMENTO] [char](1) NOT NULL,
	[DT_EXECUCAO_INI] [datetime] NOT NULL,
	[DT_EXECUCAO_FIM] [datetime] NULL,
	[CD_USUARIO_RESPONSAVEL] [int] NOT NULL,
	[IN_FINALIZADO] [char](1) NOT NULL,
 CONSTRAINT [PK_PROCESSAMENTO] PRIMARY KEY CLUSTERED 
(
	[CD_PROCESSAMENTO] ASC
)WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON) ON [PRIMARY]
) ON [PRIMARY]

GO

SET ANSI_PADDING OFF
GO

