USE [Quality_Control]
GO

IF  EXISTS (SELECT * FROM sys.foreign_keys WHERE object_id = OBJECT_ID(N'[dbo].[FK_RESUL_ENQ_CART_SUBTIP_FIL]') AND parent_object_id = OBJECT_ID(N'[dbo].[RESULTADO_ENQUADRAMENTO]'))
ALTER TABLE [dbo].[RESULTADO_ENQUADRAMENTO] DROP CONSTRAINT [FK_RESUL_ENQ_CART_SUBTIP_FIL]
GO

IF  EXISTS (SELECT * FROM sys.foreign_keys WHERE object_id = OBJECT_ID(N'[dbo].[FK_RESUL_ENQ_CARTTIP_FIL]') AND parent_object_id = OBJECT_ID(N'[dbo].[RESULTADO_ENQUADRAMENTO]'))
ALTER TABLE [dbo].[RESULTADO_ENQUADRAMENTO] DROP CONSTRAINT [FK_RESUL_ENQ_CARTTIP_FIL]
GO

IF  EXISTS (SELECT * FROM sys.foreign_keys WHERE object_id = OBJECT_ID(N'[dbo].[FK_RESULTADO_ENQUADRAMENTO_PROCESSAMENTO]') AND parent_object_id = OBJECT_ID(N'[dbo].[RESULTADO_ENQUADRAMENTO]'))
ALTER TABLE [dbo].[RESULTADO_ENQUADRAMENTO] DROP CONSTRAINT [FK_RESULTADO_ENQUADRAMENTO_PROCESSAMENTO]
GO

IF  EXISTS (SELECT * FROM sys.foreign_keys WHERE object_id = OBJECT_ID(N'[dbo].[FK_RESULTADO_ENQUADRAMENTO_USUARIO]') AND parent_object_id = OBJECT_ID(N'[dbo].[RESULTADO_ENQUADRAMENTO]'))
ALTER TABLE [dbo].[RESULTADO_ENQUADRAMENTO] DROP CONSTRAINT [FK_RESULTADO_ENQUADRAMENTO_USUARIO]
GO

IF  EXISTS (SELECT * FROM dbo.sysobjects WHERE id = OBJECT_ID(N'[DF_RESULTADO_ENQUADRAMENTO_IN_LIBERADO]') AND type = 'D')
BEGIN
ALTER TABLE [dbo].[RESULTADO_ENQUADRAMENTO] DROP CONSTRAINT [DF_RESULTADO_ENQUADRAMENTO_IN_LIBERADO]
END

GO

USE [Quality_Control]
GO

/****** Object:  Table [dbo].[RESULTADO_ENQUADRAMENTO]    Script Date: 08/26/2013 13:55:25 ******/
IF  EXISTS (SELECT * FROM sys.objects WHERE object_id = OBJECT_ID(N'[dbo].[RESULTADO_ENQUADRAMENTO]') AND type in (N'U'))
DROP TABLE [dbo].[RESULTADO_ENQUADRAMENTO]
GO

USE [Quality_Control]
GO

/****** Object:  Table [dbo].[RESULTADO_ENQUADRAMENTO]    Script Date: 08/26/2013 13:55:25 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

SET ANSI_PADDING ON
GO

CREATE TABLE [dbo].[RESULTADO_ENQUADRAMENTO](
	[CD_RESULTADO] [int] NOT NULL,
	[DT_RESULTADO] [smalldatetime] NOT NULL,
	[CD_CARTEIRA] [varchar](15) NOT NULL,
	[CD_TIPO_FILTRO] [int] NOT NULL,
	[CD_SUBTIPO_FILTRO] [int] NOT NULL,
	[CD_ATIVO] [varchar](12) NULL,
	[CD_TIPO_ATIVO] [char](2) NULL,
	[IN_ENQUADRADO] [char](1) NOT NULL,
	[VL_PONTA_A] [float] NULL,
	[VL_PONTA_B] [float] NULL,
	[DT_ABERTURA_CART] [smalldatetime] NULL,
	[DT_ENCERRAMENTO_CART] [smalldatetime] NULL,
	[DT_ALTERACAO] [datetime] NULL,
	[CD_USUARIO_ALTERACAO] [int] NULL,
	[CD_PROCESSAMENTO] [int] NULL,
	[IN_LIBERADO] [char](1) NULL,
	[DT_LIBERACAO] [datetime] NULL,
	[CD_USUARIO_LIBERACAO] [int] NULL,
	[TX_DESCRICAO] [varchar](800) NULL,
 CONSTRAINT [PK_RESULTADO_ENQUADRAMENTO] PRIMARY KEY CLUSTERED 
(
	[CD_RESULTADO] ASC
)WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON) ON [PRIMARY]
) ON [PRIMARY]

GO

SET ANSI_PADDING OFF
GO

ALTER TABLE [dbo].[RESULTADO_ENQUADRAMENTO]  WITH CHECK ADD  CONSTRAINT [FK_RESUL_ENQ_CART_SUBTIP_FIL] FOREIGN KEY([CD_SUBTIPO_FILTRO])
REFERENCES [dbo].[TIPO_FILTRO] ([CD_TIPO_FILTRO])
GO

ALTER TABLE [dbo].[RESULTADO_ENQUADRAMENTO] CHECK CONSTRAINT [FK_RESUL_ENQ_CART_SUBTIP_FIL]
GO

ALTER TABLE [dbo].[RESULTADO_ENQUADRAMENTO]  WITH CHECK ADD  CONSTRAINT [FK_RESUL_ENQ_CARTTIP_FIL] FOREIGN KEY([CD_TIPO_FILTRO])
REFERENCES [dbo].[TIPO_FILTRO] ([CD_TIPO_FILTRO])
GO

ALTER TABLE [dbo].[RESULTADO_ENQUADRAMENTO] CHECK CONSTRAINT [FK_RESUL_ENQ_CARTTIP_FIL]
GO

ALTER TABLE [dbo].[RESULTADO_ENQUADRAMENTO]  WITH CHECK ADD  CONSTRAINT [FK_RESULTADO_ENQUADRAMENTO_PROCESSAMENTO] FOREIGN KEY([CD_PROCESSAMENTO])
REFERENCES [dbo].[PROCESSAMENTO] ([CD_PROCESSAMENTO])
GO

ALTER TABLE [dbo].[RESULTADO_ENQUADRAMENTO] CHECK CONSTRAINT [FK_RESULTADO_ENQUADRAMENTO_PROCESSAMENTO]
GO

ALTER TABLE [dbo].[RESULTADO_ENQUADRAMENTO]  WITH CHECK ADD  CONSTRAINT [FK_RESULTADO_ENQUADRAMENTO_USUARIO] FOREIGN KEY([CD_USUARIO_LIBERACAO])
REFERENCES [dbo].[USUARIO] ([CD_USUARIO])
GO

ALTER TABLE [dbo].[RESULTADO_ENQUADRAMENTO] CHECK CONSTRAINT [FK_RESULTADO_ENQUADRAMENTO_USUARIO]
GO

ALTER TABLE [dbo].[RESULTADO_ENQUADRAMENTO] ADD  CONSTRAINT [DF_RESULTADO_ENQUADRAMENTO_IN_LIBERADO]  DEFAULT ('N') FOR [IN_LIBERADO]
GO

