USE [Quality_Control]
GO

IF  EXISTS (SELECT * FROM sys.foreign_keys WHERE object_id = OBJECT_ID(N'[dbo].[FK_TFA_TIPO_FILTRO]') AND parent_object_id = OBJECT_ID(N'[dbo].[TIPO_FILTRO_ATIVO]'))
ALTER TABLE [dbo].[TIPO_FILTRO_ATIVO] DROP CONSTRAINT [FK_TFA_TIPO_FILTRO]
GO

USE [Quality_Control]
GO

/****** Object:  Table [dbo].[TIPO_FILTRO_ATIVO]    Script Date: 08/26/2013 13:55:41 ******/
IF  EXISTS (SELECT * FROM sys.objects WHERE object_id = OBJECT_ID(N'[dbo].[TIPO_FILTRO_ATIVO]') AND type in (N'U'))
DROP TABLE [dbo].[TIPO_FILTRO_ATIVO]
GO

USE [Quality_Control]
GO

/****** Object:  Table [dbo].[TIPO_FILTRO_ATIVO]    Script Date: 08/26/2013 13:55:42 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

SET ANSI_PADDING ON
GO

CREATE TABLE [dbo].[TIPO_FILTRO_ATIVO](
	[CD_TIPO_FILTRO] [int] NOT NULL,
	[CD_TIPO_ATIVO] [char](2) NOT NULL,
 CONSTRAINT [PK_TIPO_FILTRO_ATIVO_1] PRIMARY KEY CLUSTERED 
(
	[CD_TIPO_FILTRO] ASC,
	[CD_TIPO_ATIVO] ASC
)WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON) ON [PRIMARY]
) ON [PRIMARY]

GO

SET ANSI_PADDING OFF
GO

ALTER TABLE [dbo].[TIPO_FILTRO_ATIVO]  WITH CHECK ADD  CONSTRAINT [FK_TFA_TIPO_FILTRO] FOREIGN KEY([CD_TIPO_FILTRO])
REFERENCES [dbo].[TIPO_FILTRO] ([CD_TIPO_FILTRO])
GO

ALTER TABLE [dbo].[TIPO_FILTRO_ATIVO] CHECK CONSTRAINT [FK_TFA_TIPO_FILTRO]
GO

